Fix the fireball spawn for small time compression factors
scp-fs2open/fs2open.github.com pull request #2716
Opened 2020-09-06 18:16 UTC by JohnAFernandez

Switches time calculation to flFrametime to fix too many explosions showing up

2020-09-06 18:19 UTC, JohnAFernandez commented
For issue #2364

2020-09-06 19:36 UTC, asarium requested changes
Can you go into detail what the original issue was?
The timestamp system exists for a very good reason since it does not suffer from floating point inaccuracies so introducing that again with these changes would be a step backwards.

2020-09-06 19:41 UTC, JohnAFernandez commented
Basically, when the screencam script is used, it reduces time compression to .001 or some crazy factor.  When that happens, timestamp starts becoming inaccurate, I assume because it lacks the resolution to properly keep time at that time compression, so many explosions will spawn instead of the amount without time compression.

2020-09-06 19:48 UTC, asarium commented
Yes, I think the time stamp system can only be accurate to something like 1/65536th of a second so at some point it will not be able to increment the timer properly and will instead increment is by 1/65536th every frame. However, I do not see how that could cause the described issues if the timestamps are reset properly after they get fired once.

Please look a bit more into this to determine if there is a fundamental timer issue here of if the relevant code maybe simply misused the timestamp system.

2020-09-06 20:04 UTC, JohnAFernandez commented
Ok.  I'll take a deeper look.

2020-09-18 14:00 UTC, JohnAFernandez commented
Ok.  It looks like you were right.  I tried writing a quick copy of the timestamp system but which uses microseconds instead of seconds and the increased resolution does not fix the problem.  It does seem like there is something wrong with the logic itself.  I will continue to investigate.

2020-09-19 01:01 UTC, JohnAFernandez commented
Turns out, afaict, it's not timestamp related at all.

2020-09-19 01:01 UTC, closed without merging