More cleanup and Int3() refactors
scp-fs2open/fs2open.github.com pull request #2744
Opened 2020-09-15 00:57 UTC by JohnAFernandez

So `ai_attack_object()` had a parameter that was intended for a future or canceled feature by :V:.  This removes the parameter without altering the logic.  -- Not extremely attached to this change

Also cleans up a bunch of `Int3()`'s in `aicode.cpp`

2020-09-15 07:03 UTC, MageKing17 requested changes
Just a couple of minor issues.

2020-09-15 07:03 UTC, MageKing17 commented on code/ai/aicode.cpp
>  		return 0;
It seems to me that it would be simpler to just have one conditional here:
```cpp
if (*ignore_objnum < 0)
{
	return 0;
}

2020-09-15 07:03 UTC, MageKing17 commented on code/ai/aicode.cpp
> +	Assertion(attacker != attacked, "%s was told to attack itself! This may be an error in the mission file.  If that checks out, please report to a coder!", Ships[attacker->instance].ship_name);
If an error in the mission file can cause this, then it shouldn't be an `Assertion()`; bad data should never trip an assertion. Given that recovery is easy from here (it recovers quite easily by just returning), it should be a `Warning()` instead.

2020-09-15 12:33 UTC, JohnAFernandez commented on code/ai/aicode.cpp
> +			Error(LOCATION, "An invalid difficulty level of %d was passed to Skill_level_names().", level);
Ok.  I did not know about that.  I will probably use that a lot more now.

2020-09-24 01:59 UTC, MageKing17 requested changes

2020-09-24 01:59 UTC, MageKing17 commented on code/ai/aicode.cpp
> +
This conditional is redundant with the one immediately below.

2021-02-23 22:04 UTC, MageKing17 approved these changes
Nothing looks wrong to me.

2021-02-24 00:51 UTC, merged

2021-02-24 00:51 UTC, JohnAFernandez commented
Thanks!