Improve Homeworld warp effect
scp-fs2open/fs2open.github.com pull request #2761
Opened 2020-09-23 03:38 UTC by Baezon

This PR might be a bit confusing if you aren't familiar with the games, but several changes were made:

Stages were added (or more accurately, unused stages were actually used) at the very beginning and end of the effect, for when the "sweeper" is a line and gaining/shrinking in width before/after gaining/shrinking in height.

The first and final two stages when the sweeper is changing size were adjusted to move more smoothly to follow the canonical motion of the effect, as well as timings adjusted.

Allow the sweeper to follow the position of the ship at all stages.

And add the sweeper-type warp to the exclusions from requiring a specific speed before the warp may commence (if a speed was not manually specified). Canonically, Homeworld ships were shown warping regardless of their speed.

2020-09-23 04:13 UTC, JohnAFernandez commented
I think this warrants a before and after video.

2020-09-23 05:10 UTC, Baezon commented
Updated.

2020-09-23 05:43 UTC, JohnAFernandez commented
Code is easy enough to follow, but I'm not sure whether I should insist on 0.0f instead of 0.f, which is how we mark it everywhere else I've seen in FSO.

2020-09-23 05:53 UTC, Baezon commented
Oh, sorry, that's something I had gotten used to. Sometimes I overlook these style/formatting habits of mine.

2020-09-23 06:05 UTC, JohnAFernandez approved these changes
An easy to read change, with video proof of an improvement.  Let's get this guy merged.

2020-09-23 07:13 UTC, asarium requested changes
I am not aware of any mods using this so any possible change in behaviour should not be an issue.

2020-09-23 07:13 UTC, asarium commented on code/ship/shipfx.cpp
> +#define HOMEWORLD_SWEEPER_LINE_THICKNESS 0.002f // How tall the initial and final hyperspace "lines" are, factor of height
Please use a `const float`.

2020-09-23 12:55 UTC, chief1983 commented
> I am not aware of any mods using this so any possible change in behaviour should not be an issue.

I know of at least The Apocalypse Project that would have previously used it.  I believe there was a separate mod at one point putting HW2 ships in FSO that might have used it too.

2020-09-23 13:29 UTC, chief1983 commented
I believe there was a public release at one point but by now it may be classified as a retired project on HLP.

2020-09-23 13:31 UTC, asarium commented
I don't think this possibly tiny compatibility issue is a problem. It can be revisited when it actually causes problems.

2020-09-23 13:37 UTC, chief1983 commented
Yeah I don't think it will either, was more trying to see if one of these mods ever release anything public so it could be tested at all.  But I can't find anything.  TAP was the HW2 mod though, I forget what the other HW1 mod was called, or if it even had a name.  I think it was just The Original Homeworld Mod or something.

2020-09-23 14:38 UTC, X3N0-Life-Form commented
The other Homeworld project was Journey to Hiigara : https://www.hard-light.net/forums/index.php?board=197.0

Both mods are dead and buried, and neither of them released any campaign, as far as I know.

2020-09-23 15:02 UTC, Baezon commented
I was actually not aware of these projects (I had started while the forums were still down)! There was also Homeworld: Pilot Academy, which is fairly old, and also didn't release a campaign (although it doesn't appear he intended to). I am currently 'remastering' it, hence my interest in this area.

Also are `const` variables always preferable to `#define`s? Sorry, I'm still in the 'try to assimilate with nearby code' phase.

2020-09-23 16:47 UTC, asarium commented
`const`s and `#define`s are mostly the same but defines can cause weird issues and do not respect scopes so if possible they should be avoided, especially for constants. Constants also give you more type safety which is always nice.

2020-09-23 16:53 UTC, chief1983 commented
I double checked and I did see Journey to Hiigara earlier, but there was also a project for HW1 contained solely in one forum thread, named "The Original Homeworld Mod".   So that's at least 4 projects that might have made use of this, yet with no public releases I can find.  So yeah, nothing to worry about with this change apparently.

2020-09-23 18:18 UTC, Goober5000 commented
Why does the engine glow turn off while the square is moving?  It then reappears when the ship model has disappeared.

2020-09-23 18:20 UTC, asarium approved these changes

2020-09-23 18:21 UTC, Baezon commented
The orientation of warp effect was done inconsistently with the retail one. I have since fixed it.

2020-09-24 01:33 UTC, merged

2020-09-24 01:33 UTC, JohnAFernandez commented
Looks like it's time to merge.  Well done!