Fix multiplayer stat save
scp-fs2open/fs2open.github.com pull request #2918
Opened 2020-11-22 19:59 UTC by JohnAFernandez

When pressing escape, it was previously possible to attempt saving the stats multiple times, but this will keep it to just one attempt.

2020-11-23 00:07 UTC, notimaginative commented
Not sure that I like this. The point of that flag was to indicate that stats were stored, not that they *might* have been stored.

I may have misunderstood the problem of at which point the ESC key is hit. If it's on the debriefing screen then I think that's a different issue. If it's actually during stats save this probably needs a fix in `multi_fs_tracker_store_stats()` instead.

2020-11-24 00:50 UTC, notimaginative requested changes
I'd rather the netgame flag remain as-is so that it's still relevant.

But it should be possible to just add a boolean local to multiui which accomplishes the same result that this change does. Then use that boolean instead of the `if ( !(Netgame.flags & NG_FLAG_STORED_MT_STATS) )` check in both `multi_debrief_accept_hit()` and `multi_debrief_esc_hit()`.

Otherwise I haven't found a better way to address this than what you're attempting .

2020-11-26 03:39 UTC, JohnAFernandez commented
All right, how about this?

2020-11-26 03:51 UTC, notimaginative approved these changes

2020-11-26 03:52 UTC, notimaginative commented
LGTM, thanks!

2020-11-26 17:13 UTC, merged