Modified Ship-Ship Collision Overrides to fit other Ship-X collision Overrides
scp-fs2open/fs2open.github.com pull request #2954
Opened 2020-12-03 22:43 UTC by SelfGamer

Refers to Issue #2953 
All I've done to fix this, is move some code. Namely, the function ship_ship_check_collision (which is supposed to _check_ if there is a collision) contained some code to already handle and process the collision (push objects around and notify AI). This code, I've moved after the override checks of the lua API. I did not modify this code (apart from the renaming of variables that were passed down into the function and the subsequent direct accessing as opposed to dereferencing the passed pointers) and copied it as a whole block.
Note, that the other functions for detection of those collisions (debris_check_collision, asteroid_check_collision, and so on) do exactly that, and only do detection and not physics handling, which is then processed after checking the override, in a comparable manner as to how ship ship now works.

2020-12-03 23:11 UTC, Baezon commented
Generally looks good to me, I might want to see someone more qualified review whether this was indeed intentional, but otherwise ok if you've tested to make sure normal and overridden collisions work as they should now.

2020-12-03 23:13 UTC, SelfGamer commented
> Generally looks good to me, I might want to see someone more qualified review whether this was indeed intentional, but otherwise ok if you've tested to make sure normal and overridden collisions work as they should now.

Yeah, would probably be good to have someone familiar with this code check as well.
In my test scenario, it worked properly, but I only tested tens of collisions not hundreds.

2020-12-03 23:26 UTC, Baezon commented
Ah well its not about the number of collisions but the weird obscure edge cases we didn't think of when it comes to bugs. What you've already done should be fine.

2020-12-04 00:44 UTC, Goober5000 requested changes
Looks good.  This was almost certainly an idiosyncratic implementation choice by Volition that didn't harm anything because of the original code flow.  When the scripting coder added the hook, it probably didn't occur to him to move the "valid hit occurred" code.

The only thing I would suggest is to put a comment above and below the block of code, saying that it was moved from its original location in `ship_ship_check_collision`.

2020-12-04 01:40 UTC, SelfGamer commented
> Looks good. This was almost certainly an idiosyncratic implementation choice by Volition that didn't harm anything because of the original code flow. When the scripting coder added the hook, it probably didn't occur to him to move the "valid hit occurred" code.
> 
> The only thing I would suggest is to put a comment above and below the block of code, saying that it was moved from its original location in `ship_ship_check_collision`.

Alright, marked the codeblock. Thanks for checking.

2020-12-04 01:48 UTC, Goober5000 approved these changes
:+1:

2020-12-04 20:28 UTC, merged