Improved missile avoidance
scp-fs2open/fs2open.github.com pull request #3177
Opened 2021-01-27 20:29 UTC by Baezon

What it says on the tin, no more AI eating trebs!

Actual changes are a variety of things: only drop countermeasures if the missile is within cm range, always dodge even if you have countermeasures, don't dodge too early, afterburn based on time to impact, not distance, only consider evading missiles actually pointing at you, and better evasion maneuvers (the old method was very strange and not particularly effective).

While they are much better overall there are still reasonable limitations, difficulty affects whether the AI can afterburn, and there are many reasonable situations where the AI simply can't react in time; this doesn't turn AI into superhumans.

Fixes #2951, also sorry @tcrayford but this kinda obviates #2096 as well.

2021-01-28 20:15 UTC, Goober5000 requested changes
Looks reasonable I think.  One nitpick.

2021-01-28 20:15 UTC, Goober5000 commented on code/ai/ai_profiles.cpp
> +				set_flag(profile, "improved missile avoidance for fightercraft:", AI::Profile_Flags::Improved_missile_avoidance);
This should probably have a dollar sign at the beginning of the line.

2021-01-29 20:11 UTC, wookieejedi commented
Looking forward to testing this one.

2021-01-29 23:40 UTC, Goober5000 approved these changes

2021-01-30 03:47 UTC, merged