Added flag to select the warp effect type of LSSM's
scp-fs2open/fs2open.github.com pull request #3259
Opened 2021-02-28 15:10 UTC by BMagnu

Implements #3236.
Code is pretty much copied from how the fireball type is inferred for SSM's

2021-02-28 23:04 UTC, Baezon requested changes
This isn't quite what the issue was referring to, I believe he was referring to different styles of warp, like the BSG in place animation or the Homeworld sweeper, which would require more complex changes.

Still, a welcome change and I would like to add at least the in place anim to this at some point.

2021-02-28 23:04 UTC, Baezon commented on code/weapon/weapons.cpp
> +					error_display(0, "Unknown fireball [%s] to use as warp effect for LSSM weapon", unique_id);
Why not throw in the name in the warning message as well? If you're Eatthepath 'an LSSM weapon' might not narrow it down much ;)

2021-03-01 06:22 UTC, Baezon approved these changes

2021-03-01 07:28 UTC, EatThePath commented
> This isn't quite what the issue was referring to, I believe he was referring to different styles of warp, like the BSG in place animation or the Homeworld sweeper, which would require more complex changes.
> 
> Still, a welcome change and I would like to add at least the in place anim to this at some point.

My intention was to request both, so this doesn't implement all of the FR, but it does implement a worthwhile portion of it

2021-03-02 08:07 UTC, merged