Fix probability distribution of vm_vec_random_in_circle/sphere
scp-fs2open/fs2open.github.com pull request #3284
Opened 2021-03-11 08:11 UTC by Baezon

Randomly getting a point on a circle/sphere edge and scaling inward by `frand()` is *not* a uniform distribution, as the comments say, this will bias the distribution towards the center, so introduce a factor to combat this. The only thing that should be noticeably affected is beam aim 'jitter', since this is retail an optional parameter is added to to maintain this 'bias' (and also for trails because they look better that way)

As an aside, randomizing a vector's coordinates and normalizing is *also* not a uniform distribution over a spherical surface (ironically that method was introduced in the same PR that introduced the proper method for random_cone, which has been used for circle and sphere now).

2021-03-12 17:28 UTC, Goober5000 requested changes
A few thoughts

2021-03-12 17:28 UTC, Goober5000 commented on code/math/vecmat.cpp
> +	// sqrt because scaling inward increases the probability desnity by the square of its distance towards the center
density

2021-03-12 17:28 UTC, Goober5000 commented on code/math/vecmat.cpp
> +	// cube root because scaling inward increases the probability desnity by the cube of its distance towards the center
density

2021-03-12 17:28 UTC, Goober5000 commented on code/math/vecmat.cpp
> +	vm_vec_scale_add(out, in, &temp, on_surface ? radius : powf(util::UniformFloatRange(0.0f, 1.0f).next(), 0.333f) * radius);
It would be nice to have a `bias_towards_center` parameter just like the companion function

2021-03-12 17:28 UTC, Goober5000 commented on code/weapon/beam.cpp
>  	// get a vector on the circle - this should appear to be pretty random
Edit the comment to clarify it's random with a bias.  I know the `true` parameter should suffice but people might read just the comment and not look at that.

2021-03-13 20:35 UTC, Goober5000 requested changes
Looks good.  One last request: Could you enhance the `randomInCircle` and `randomInSphere` scripting functions to use the new optional parameter?

2021-03-13 20:39 UTC, Baezon commented
Hmm, I suppose it should default to true for better backwards compatability?

2021-03-13 20:50 UTC, Goober5000 commented
> Hmm, I suppose it should default to true for better backwards compatability?

Yup.

2021-03-13 20:52 UTC, Goober5000 commented
> Hmm, I suppose it should default to true for better backwards compatability?

Defaulting to false is fine, and I think it is better for future proofing.  Just make sure the scripting functions use the compatible default and you should be okay.

2021-03-13 21:03 UTC, Baezon commented
As in, both the internal and scripting function should default to false (but allow for true if you want)?

2021-03-13 21:07 UTC, Goober5000 commented
> As in, both the internal and scripting function should default to false (but allow for true if you want)?

I was thinking that the internal function should default to no biasing, but the scripting function should default to biasing to remain compatible with previous scripts.

2021-03-17 19:04 UTC, Goober5000 approved these changes
Very nice. :+1:

2021-03-19 06:23 UTC, merged