Strip hashes from explicitly defined ship display names in tables.
scp-fs2open/fs2open.github.com pull request #3348
Opened 2021-03-31 21:34 UTC by TRBlount

This was an oversight from the last changing relating to alt names. This will apply the same hash stripping rules to display/alt names as are applied to normal ship names when generating a display name automatically.

2021-03-31 21:35 UTC, JohnAFernandez approved these changes
Knock another one down.

2021-04-01 02:03 UTC, Goober5000 requested changes
Wait, what?  This isn't an oversight at all; this is how display names with hashes are supposed to be specified.

2021-04-01 02:08 UTC, TRBlount commented
The issue is that people are confused by the terminology and expect `$Display Name:` to strip as well. I mentioned this as well, but some discussion made it seem like not stripping hashes from `$Display Name:` was incorrect behavior based on previous PRs. How should we handle this then?

2021-04-01 03:30 UTC, MageKing17 commented
It's a backwards-incompatibility; mods were made with the assumption that the display name would be hash-stripped, and now they aren't. We don't have to worry about breaking retail in this instance, but it's really not that much effort to make the behavior both consistent with people's expectations *and* with how mods were made for years.

2021-04-02 01:42 UTC, Goober5000 commented
I caught up on the conversation.  Given the amount of confusion this has caused, I agree with returning to hash truncation even on display names, and adding the double-hash escape sequence.  2018 wasn't *that* long ago, but it's long enough, and Release 19 would have had the truncation behavior.

2021-04-02 01:45 UTC, Goober5000 requested changes
Additional steps required:

1) Truncate hashes on weapon classes as well
2) Add the double-hash escape sequence for ship class display names
3) Add the double-hash escape sequence for weapon class display names

2021-04-02 03:59 UTC, Goober5000 commented
Once #3353 is merged, the `consolidate_double_characters` function can be reused for this PR.

2021-04-06 03:51 UTC, Goober5000 commented
And it's merged.

2021-04-17 23:09 UTC, TRBlount commented
> Additional steps required:
> 
> 1. Truncate hashes on weapon class display names as well
> 2. Add the double-hash escape sequence for ship class display names
> 3. Add the double-hash escape sequence for weapon class display names

@Goober5000 This should be handled in the latest version of the PR.

2021-04-18 04:43 UTC, Goober5000 approved these changes
Looks good.

2021-04-18 04:44 UTC, Goober5000 commented
> Also, we might wish to extend `consolidate_double_characters()` to handle multiple characters at once (ie. make the second parameter `char*` instead of `char`).

When would we need to do that?

2021-04-18 04:47 UTC, TRBlount commented
Not sure yet tbqh. It was just an idea I had since functions like that often have the ability to handle multiple types of characters. (See: Boost libs string parsing functions)

2021-04-18 05:03 UTC, merged