Validate user-provided values passed to Random::next()
scp-fs2open/fs2open.github.com pull request #3464
Opened 2021-05-31 23:50 UTC by jg18

Validate values supplied to `rand` and `rand-multiple` SEXPs and also to `rand32()` scripting function before calling `Random::next()`, and issue a warning if the provided values are invalid.

Fixes issue #3459.

2021-05-31 23:53 UTC, JohnAFernandez approved these changes

2021-06-01 02:52 UTC, Goober5000 requested changes

2021-06-01 02:52 UTC, Goober5000 commented on code/parse/sexp.cpp
> +		return SEXP_KNOWN_FALSE;
This should return `low`, both for compatibility reasons (it's what used to be returned) and because caller sexps expect a number, not a boolean.

2021-06-01 02:52 UTC, Goober5000 commented on code/scripting/api/libs/base.cpp
> +			result = 0;
This should also return `low` to match the sexp.

2021-06-01 03:39 UTC, Goober5000 approved these changes

2021-06-01 03:59 UTC, jg18 commented
I'll wait to get @asarium's thoughts before I merge this.

2021-06-01 15:57 UTC, asarium requested changes

2021-06-01 15:57 UTC, asarium commented on code/scripting/api/libs/base.cpp
> +			Warning(LOCATION, "rand32() script function was passed an invalid range (%d ... %d)!", a, b);
This and the other should be a `LuaError` since that will give the script user a stack trace in their script.

2021-06-02 16:45 UTC, asarium approved these changes

2021-06-02 16:52 UTC, merged