Force portable if unicode
scp-fs2open/fs2open.github.com pull request #3562
Opened 2021-07-18 05:40 UTC by JohnAFernandez

This allows FSO to assume that it's in portable mode if it detects Unicode characters in the path provided by SDL.  I tested this by creating a local account with Unicode characters.  It not only runs as expected, but also keeps Knossos from getting stuck on the executable when trying to parse the command line.  

Fixes #3173

2021-07-18 05:41 UTC, JohnAFernandez commented on code/osapi/osapi.cpp
> +bool Force_Portable_Mode = false;
Btw, not sure if this is the best place to put this because I had to use extern bool and therefore had to put it outside the anonymous namespace.

2021-07-18 19:24 UTC, Goober5000 reviewed
This looks good, but why not set the `Cmdline_portable_mode` flag instead?

2021-07-18 19:26 UTC, JohnAFernandez commented
I thought it was better to keep it separate, but that's only based on a guess for best practices.  I can go either way.

2021-07-18 19:31 UTC, Goober5000 approved these changes
I would use a single flag.  The reason is that every place where portable mode needs to be handled, the engine now needs to check two flags instead of one.

You already added the `force_portable_warning` to indicate whether the forcing actually took place.  If we need to remember the context we can give that variable a wider scope.

2021-07-18 19:32 UTC, Goober5000 requested changes
(hit the wrong option)

2021-07-18 19:33 UTC, JohnAFernandez commented
> I would use a single flag. The reason is that every place where portable mode needs to be handled, the engine now needs to check two flags instead of one.
> 
> You already added the `force_portable_warning` to indicate whether the forcing actually took place. If we need to remember the context we can give that variable a wider scope.

Ok.  That shouldn't be hard to change.

2021-07-23 02:59 UTC, JohnAFernandez commented
Changed.

2021-07-23 05:00 UTC, Goober5000 commented on code/osapi/osapi.cpp
> +								"the commandline to avoid in the future",
To be unambiguous, say "to avoid this message", or something similar.

2021-07-25 18:10 UTC, Goober5000 approved these changes
:+1:

2021-07-25 18:18 UTC, merged

2021-08-07 21:42 UTC, ngld commented
I think this will cause FSO to ignore all `fs2_open.ini` settings since Knossos doesn't support portable mode and will still place that file in the user's `AppData` folder which FSO can't access. FSO ignoring those settings is still better than crashing on launch, though.