Fix homing child weapons in niche circumstances
scp-fs2open/fs2open.github.com pull request #3661
Opened 2021-09-17 23:18 UTC by EatThePath

This line, in code that runs if a seeker's range to target ever increases noticeably, removes the target_num but doesn't touch the values that are primarily used for homing. The only effect it has that I've been able to find is to break the inherit parent target weapon flag, which checks the target number.

2021-09-19 21:35 UTC, Baezon approved these changes

2021-09-19 21:45 UTC, Goober5000 requested changes
One thing that *will* change is that it will cause the "If our target is still valid, then update some info." block to be run every frame, since it checks `target_num`.  Will this have any effect?

2021-09-19 21:52 UTC, Baezon commented
After some investigation, it appears that both `lead_scale` and `nearest_dist` are used by literally nothing. They are initialized elsewhere and updated by this block, and that's it. >.>

Given that this whole block might just be deleted. This is clearly not a 'lost your target' situation so it really shouldn't be setting `target_num` to -1.

2021-09-19 21:53 UTC, EatThePath commented
> 
> 
> After some investigation, it appears that both `lead_scale` and `nearest_dist` are used by literally nothing. They are initialized elsewhere and updated by this block, and that's it. >.>
> 
> Given that this whole block might just be deleted. This is clearly not a 'lost your target' situation so it really shouldn't be setting `target_num` to -1.

I can expand the pr to just clean that all out then, in that case.

2021-09-19 21:54 UTC, Baezon commented
Make sure to give it another round of testing as well, to be sure.

2021-09-21 03:01 UTC, EatThePath commented
@asarium sorry about that, sloppy keyboarding and sloppy git-fu accidentally made a spurious white-space change to a scripting file, since force-pushed out of the timeline.

2021-09-21 21:57 UTC, EatThePath commented
> 
> 
> One thing that _will_ change is that it will cause the "If our target is still valid, then update some info." block to be run every frame, since it checks `target_num`. Will this have any effect?

As Asteroth indicated, the data being updated is data only ever used in this section of the code anyway. As far as I can tell everything in the if block indicated by that comment might as well be a noop as far as the rest of the simulation is concerned, except the line I was deleting to begin with. With my last push, it's all torn out now.

2021-09-22 01:36 UTC, Goober5000 approved these changes
Ok.

2021-09-22 01:37 UTC, Goober5000 commented
Let's not merge this until after 21.4 is out though.

2021-09-28 05:42 UTC, merged