Remove light filtering data
scp-fs2open/fs2open.github.com pull request #3737
Opened 2021-10-17 16:31 UTC by EatThePath

`light_ignore_objnum` and `affected_objnum` support features that, as far as I can determine, can't work in deferred and don't even work in non-deferred lighting. Their continued presence in the code is a distraction.

Submitted in draft at the moment because my ability to actually test these changes has been very limited.

2022-04-02 15:38 UTC, EatThePath commented
The commit log mess is from me rebasing on current master . I can withdraw this PR and resubmit the changes in a new branch if that's going to make a mess.

2022-04-04 17:03 UTC, EatThePath commented
@wookieejedi It's hard to prove a negative, which is the situation here as I don't see how the removed code would have any visible impact on the game. However I've run the game in lighting heavy situations both with and without the change, and with and without -no_deferred, and I can see no difference to my eye.

2022-04-05 16:36 UTC, asarium approved these changes
I agree that such a feature is not possible to implement in our current lighting setup so there is no reason to keep this code.

2022-04-10 14:00 UTC, z64555 requested changes
Looks good otherwise for a few style/formatting nitpicks

2022-04-24 00:29 UTC, z64555 approved these changes

2022-04-24 00:30 UTC, z64555 commented
Final call for testing before merge.

2022-04-24 22:10 UTC, EatThePath commented
I've been working this weekend on a branch incorporating these changes and they're working fine, so I'm pushing the button

2022-04-24 22:12 UTC, merged