Fix Weapon-Loadout-Specific Models
scp-fs2open/fs2open.github.com pull request #3796
Opened 2021-11-23 07:46 UTC by BMagnu

By specifying a different techroom model, the weapon loadout screen can display a different model than used ingame.
However, when loaded it would also reinitialize the model_subsystems of the ship_info, and thus change the model_num of the subsystems. This causes a bunch of problems down the line. Since the recent change to subsystem rotation handling, a corrupt model_num can just cause straight CTD's on mission start.

This addresses this by not loading the ship_info's subsystems with the techmodel, but a seperate submodel buffer.

2021-11-23 16:17 UTC, Goober5000 requested changes
Instead of using a temporary subsystem buffer, why not just pass `0, nullptr` to `model_load`?  It looks like this is done in several other places in the code already.

2021-11-23 16:23 UTC, BMagnu commented
Fair, that works too.

2021-11-23 16:31 UTC, Goober5000 approved these changes

2021-11-24 18:07 UTC, JohnAFernandez approved these changes

2021-11-24 18:07 UTC, merged