Substitute Ship Label
scp-fs2open/fs2open.github.com pull request #3798
Opened 2021-11-25 17:11 UTC by TaGenius

Implement #3757 Adding a new optional line to the missionfile for a briefing icon $Closeup label after $label. Currently has to be added in text editor though i have added a field in QTFred's briefing editor for when someone completes it.

2021-11-30 13:10 UTC, TheForce172 commented
Realised I forgot screenshots
![image](https://user-images.githubusercontent.com/2040992/144051976-8a936bff-cf88-4b49-b28d-c771176b5a48.png)
![image](https://user-images.githubusercontent.com/2040992/144053237-b6d72dcf-1cd6-4b9c-ab4c-2f98e2ab4e12.png)

2021-11-30 13:10 UTC, TheForce172 commented
Screenshots
![image](https://user-images.githubusercontent.com/2040992/144053367-2f1fe94c-e9f1-419d-b339-415c0e0091e6.png)
![image](https://user-images.githubusercontent.com/2040992/144053312-9657ee10-e76a-4386-9d25-70e8359f4381.png)

2021-12-01 01:04 UTC, EatThePath reviewed
fwiw, the code for this looks straight forward and solid to me.

2021-12-06 23:46 UTC, Goober5000 requested changes

2021-12-06 23:46 UTC, Goober5000 commented on fred2/missionsave.cpp
> +				if (drop_white_space(bi->customClass)[0]) {
Add a `Mission_save_format != FSO_FORMAT_RETAIL` check here.

2021-12-06 23:46 UTC, Goober5000 commented on qtfred/src/mission/missionsave.cpp
> +				if (drop_white_space(bi->customClass)[0]) {
Add a `save_format != MissionFormat::RETAIL` check here.

2021-12-07 03:14 UTC, Goober5000 approved these changes
Looks good

2021-12-08 18:17 UTC, merged