QTFRED: Ship Editor Cleanup 2
scp-fs2open/fs2open.github.com pull request #4237
Opened 2022-04-30 22:19 UTC by TheForce172

More clean-up for the ship editor

1. Only create new dialog on first opening, should reduce memory usage.
2. Fix crash bug in player orders dialog
3. Add tooltips

2022-05-08 19:36 UTC, JohnAFernandez commented on qtfred/src/ui/dialogs/ShipTextureReplacementDialog.cpp
> +			ShipTextureReplacementDialog::ShipTextureReplacementDialog(QDialog* parent, EditorViewport* viewport)
Is this functionality being lost?

2022-05-08 19:52 UTC, TheForce172 commented on qtfred/src/ui/dialogs/ShipTextureReplacementDialog.cpp
> +			ShipTextureReplacementDialog::ShipTextureReplacementDialog(QDialog* parent, EditorViewport* viewport)
No it been moved down to line 46-48

2022-05-17 14:09 UTC, TheForce172 commented on qtfred/src/mission/dialogs/PlayerOrdersDialogModel.h
> +			  void initialiseData(bool);
These were made public so that the dialog can reload the model if the ship editor moves to another ship.

2022-05-17 14:10 UTC, TheForce172 commented on qtfred/src/ui/dialogs/ShipEditorDialog.h
> +	ShipGoalsDialog* GoalsDialog = nullptr;
Probably, I'll wait for more experienced heads to comment.

2022-06-04 14:02 UTC, z64555 requested changes
I apologize for the delay.  I've been kept busy and haven't gotten momentum back yet.

Looks mostly good except for a few spots.  I still need to read up on the usage of std::unique_ptr, so I've just pointed them out so that other reviewers can look at them quickly.

2022-06-10 22:51 UTC, TheForce172 commented on qtfred/src/ui/dialogs/ShipEditorDialog.cpp
> +		if (!(The_mission.game_type & MISSION_TYPE_MULTI) && _model->getNumSelectedObjects() && !_model->getIfMultipleShips() && isPlayerWing)
Should be Resolved

2022-06-10 23:00 UTC, TheForce172 commented on qtfred/src/ui/dialogs/ShipEditorDialog.cpp
> +	_model->setShipName(text);
I'm going to need some help here, _model->setShipName() is a reference operation I believe as clang complains if it isn't. But from what you say this isn't safe ether?

2022-09-17 13:49 UTC, z64555 approved these changes
LGTM.

2022-09-17 20:51 UTC, merged