Replace "Always_show_goals" with "Toggle_showing_goals"
scp-fs2open/fs2open.github.com pull request #4263
Opened 2022-05-12 22:09 UTC by naomimyselfandi

The "Always_show_goals" flag is a no-op on anything other than a training mission. This replaces it with a new flag which toggles whether the goals are shown instead, in keeping with the existing "Toggle_debriefing" flag.

2022-05-12 23:11 UTC, Goober5000 requested changes
Everything here looks good.  But a few more changes will need to be made in fred2\missionnotesdlg.cpp and qtfred\src\ui\dialogs\MissionSpecDialog.cpp due to the variable change.

2022-05-12 23:15 UTC, naomimyselfandi commented
Huh. I thought I'd also built FRED, but I guess I mustn't have.

2022-05-13 00:01 UTC, Goober5000 requested changes
Two more things.  Happily, these only need to be done in FRED, as whoever added the qtFRED flags thought ahead.

2022-05-13 00:04 UTC, naomimyselfandi commented on fred2/missionnotesdlg.cpp
> -	m_always_show_goals = (The_mission.flags[Mission::Mission_Flags::Always_show_goals]) ? 1 : 0;
I think you're commenting on the removed version of this line.

2022-05-13 00:05 UTC, naomimyselfandi commented on fred2/missionnotesdlg.cpp
>  	// always show mission goals
Good catch.

2022-05-13 00:15 UTC, Goober5000 commented on fred2/missionnotesdlg.cpp
> -	m_always_show_goals = (The_mission.flags[Mission::Mission_Flags::Always_show_goals]) ? 1 : 0;
I'm referring to the `m_always_show_goals` member variable of CMissionNotesDlg, not the flag name.

2022-05-13 00:30 UTC, naomimyselfandi commented on fred2/missionnotesdlg.cpp
> -	m_always_show_goals = (The_mission.flags[Mission::Mission_Flags::Always_show_goals]) ? 1 : 0;
Wow, I totally didn't see that. I caught a few other stale names and I think I've updated all of them.

2022-05-13 00:48 UTC, Goober5000 approved these changes
Looks good now. 👍 

I would also suggest removing `IDC_TOGGLE_SHOWING_GOALS2`, since that isn't used anywhere, but that doesn't need to hold up the PR.

2022-05-14 03:10 UTC, z64555 commented on code/missionui/missionbrief.cpp
> +	if (The_mission.flags[Mission::Mission_Flags::Toggle_showing_goals] == !!(The_mission.game_type & MISSION_TYPE_TRAINING)) {
What, "!!" What's that about?

2022-05-14 03:18 UTC, z64555 commented on code/missionui/missionbrief.cpp
> +	if (The_mission.flags[Mission::Mission_Flags::Toggle_showing_goals] == !!(The_mission.game_type & MISSION_TYPE_TRAINING)) {
I see now, the `!!` cleans the bit mask its operating on into a proper boolean.

2022-05-14 03:19 UTC, merged