Allow SCPUI to run `$On Briefing Stage:` hooks
scp-fs2open/fs2open.github.com pull request #4275
Opened 2022-05-15 23:47 UTC by naomimyselfandi

BTA added a script that listens for briefing stages. It works fine for regular briefings, but not for command briefings. Mjn realized that SCPUI (which we use for CBs, but not regular briefings) wasn't triggering the `$On Briefing Stage:` hooks. This adds a scripting function to trigger them.

2022-05-15 23:50 UTC, naomimyselfandi commented
@asarium, I'm sorry, it looks like I (somehow) accidentally sent you a review request...?

2022-05-15 23:56 UTC, Goober5000 requested changes
The briefing stage hook is not run for command briefings, nor is there currently an `$On Command Briefing Stage` hook.  It would be better to implement that hook.

2022-05-16 00:22 UTC, naomimyselfandi commented
> The briefing stage hook is not run for command briefings

It's called in `cmd_brief_new_stage(int)` on line 364 of `missionui/missioncmdbrief.cpp`.

2022-05-16 05:26 UTC, Goober5000 commented
Wow, you're right.  I ran a couple of searches but I completely missed that.

But that just moves the explanation from obvious to puzzling.  How does SCPUI run the hooks for the regular briefings?

2022-05-16 11:37 UTC, naomimyselfandi commented
> But that just moves the explanation from obvious to puzzling. How does SCPUI run the hooks for the regular briefings?

Oh, there's a (disappointingly) simple answer here. SCPUI doesn't support every screen yet, and briefings are (understandably, given how complex they are) one of the ones that aren't. You can observe this in BTA, depending on your screen resolution; the command briefing uses the whole screen, while the briefing is letterboxed.

When it does support briefings, a similar function should be provided.

2022-05-17 01:12 UTC, Goober5000 commented
Ok, I think I understand now.  Since SCPUI rolls its own interface, it doesn't fire script hooks for cbrief *or* brief, but you only use SCPUI for cbrief.

This type of solution didn't sit right with me - and still doesn't - because it's a sort of brute-force invocation of another part of the code that should be part of the normal flow.  (It would be good to get @asarium 's input if possible.)

There is one more avenue that should be explored.  In `ui_system-sct.lua`, there are several `addHook` instances which appear to link up with the standard state transitions.  Have you tried adding briefing hooks in a similar way?  It's my hunch that this might be what you're looking for.

2022-05-17 08:58 UTC, asarium commented
At least in my opinion, this solution is fine for now. Sure, a generic system for invoking Lua hooks from Lua might be nice but would be overkill in this case.

2022-05-17 11:53 UTC, naomimyselfandi commented
> but you only use SCPUI for cbrief

SCPUI does not support non-command briefings at this time.

>  It's my hunch that this might be what you're looking for.

boolean addHook(string name, function() -> void hookFunction, [table conditionals (Empty table by default), function() -> boolean override_func (Function returning false by default)])
    Adds a function to be called from the specified game hook
    Returns: true if hook was installed properly, false otherwise

> This type of solution didn't sit right with me - and still doesn't - because it's a sort of brute-force invocation of another part of the code that should be part of the normal flow.

SCPUI is already outside of the normal flow. If you have another suggestion based on something more substantive than a hunch, I'd love to hear it.

2022-05-17 18:16 UTC, Goober5000 commented
> boolean addHook(string name, function() -> void hookFunction, [table conditionals (Empty table by default), function() -> boolean override_func (Function returning false by default)])
Adds a function to be called from the specified game hook
Returns: true if hook was installed properly, false otherwise

Yeah, that's almost the opposite of what we need here.

> SCPUI is already outside of the normal flow. If you have another suggestion based on something more substantive than a hunch, I'd love to hear it.

Hunches can be useful; they have helped me track down some esoteric issues including #4013.

I'm satisfied with the discussion at this point, especially after getting @asarium 's feedback.  Will approve.

2022-05-17 18:16 UTC, Goober5000 approved these changes

2022-05-18 22:47 UTC, merged