Allow Weapon To Override Turret Name
scp-fs2open/fs2open.github.com pull request #4313
Opened 2022-05-26 11:00 UTC by TheForce172

Done following a discussion in #Freespace a week or so ago. Allows a weapon to override a turrets name if it is the first weapon in a turret. Does not override a Subsystems Alt name if specified in ships.tbl

2022-05-26 16:51 UTC, Baezon requested changes

2022-05-26 16:51 UTC, Baezon commented on code/hud/hudtargetbox.cpp
> +		}
Perhaps it should search through all the banks instead of just checking the first ones?

2022-05-28 19:55 UTC, merged

2022-05-28 19:57 UTC, Goober5000 commented on code/hud/hudtargetbox.cpp
> +				if (weaponid >= 0) {
Why not loop from 0 to `swp->num_primary_banks`?  All weaponids after that point are going to be -1 anyway.

2022-05-28 19:57 UTC, Goober5000 commented on code/hud/hudtargetbox.cpp
> +					if (strlen(Weapon_info[weaponid].altSubsysName) != 0) {
I would check that the string is non-empty (checking that the first character != 0) rather than getting the length.

2022-05-28 19:57 UTC, Goober5000 commented on code/hud/hudtargetbox.cpp
>  				}
Same comments here.

2022-05-28 19:58 UTC, Goober5000 commented
Ack, badly timed...