Support using containers with random-multiple-of SEXP
scp-fs2open/fs2open.github.com pull request #4326
Opened 2022-05-29 06:37 UTC by jg18

Support using list containers of strings and map containers with string keys as arguments to `random-multiple-of`.

Depends on PR #4305.

Would appreciate help with testing.

With my current test mission ([test_random_multiple_of.fs2.txt](https://github.com/scp-fs2open/fs2open.github.com/files/8792805/test_random_multiple_of.fs2.txt)) when I press "2", random messages get sent out over and over on what feels like an infinite loop. I can't tell if it's a code bug or if my test mission is just buggy (I'm not a FREDder).

2022-05-29 06:40 UTC, jg18 commented
Tip: Once again, using the "Ignore whitespace" option under the "Files changed" tab shrinks the PR a bit and makes it easier to see what's changed.

2022-05-30 01:06 UTC, Karajorma commented
Yeah, the problem was a FREDding issue. Key-reset is notoriously buggy with certain keys. Switching to Key-reset-multiple fixes the mission and it then works perfectly.

2022-06-03 07:43 UTC, BMagnu requested changes
A minor detail.
While the split of random-of and random-multiple-of is annoying, I understand why we need it, as random-of is fundamentally incompatible with the dynamic nature of the containers.

2022-06-03 07:43 UTC, BMagnu commented on code/parse/sexp.cpp
> +		SCP_UNUSED(num_args);
This is kind of weird.
Instead of avoiding the warning with a macro, you should just not store the result.

2022-06-03 22:57 UTC, BMagnu approved these changes

2022-06-04 00:09 UTC, merged