Changelog.py improvements and post-release-build.yaml debugging
scp-fs2open/fs2open.github.com pull request #4380
Opened 2022-06-10 13:19 UTC by z64555

This adds an `echo` to print out the `github.event_name` of the calling workflow, so that the Auto Trigger can be debugged. (For some reason it hasn't been firing when called by Release.yaml)

Fixes Changelog.py going into an infinite loop due to not breaking out when page = last_page + 1, issue turned out to be due to how `for .. in ..` loops differ from C++'s `for` loops.

Also makes some improvements to the Changelog.py to be more user friendly as well as allow authentication to get around the REST API HTTP requests limits.

2022-06-10 13:22 UTC, MageKing17 commented on ci/post/changelog.py
> +    while page < last_page + 1:
I think it would be clearer like this:
```suggestion
    while page <= last_page:
```

2022-06-10 21:13 UTC, MageKing17 requested changes
Couple typos in the description, but otherwise changes look good.

2022-06-10 21:13 UTC, MageKing17 commented on ci/post/changelog.py
> +    parser = argparse.ArgumentParser(description="Retrives a log of commit messages and attempts to pretty them into a human-readbile format")
```suggestion
    parser = argparse.ArgumentParser(description="Retrieves a log of commit messages and attempts to pretty them into a human-readable format")
```

2022-06-14 05:05 UTC, MageKing17 approved these changes
No idea what this particular CI failure means, but the code seems fine.

2022-06-14 13:17 UTC, z64555 commented
> No idea what this particular CI failure means, but the code seems fine.

Hmm, I'm not seeing any failures on the PR checks. Where do you see the failures?

2022-06-15 05:26 UTC, MageKing17 commented
> > No idea what this particular CI failure means, but the code seems fine.
> 
> Hmm, I'm not seeing any failures on the PR checks. Where do you see the failures?

Someone must've re-ran it... it was a strange failure about being unable to create a symlink, I think; hopefully just a fluke.

2022-06-15 05:26 UTC, merged

2022-06-15 12:12 UTC, z64555 commented
> > Hmm, I'm not seeing any failures on the PR checks. Where do you see the failures?
> 
> Someone must've re-ran it... it was a strange failure about being unable to create a symlink, I think; hopefully just a fluke.

linux gcc-10 has been failing at random but frequent times due to a "file exists" error.  See #4350