add some logging to waitAsync
scp-fs2open/fs2open.github.com pull request #4448
Opened 2022-06-27 00:06 UTC by Goober5000

Log when the context is created, completes, and is aborted.  Adds insight for the situation described in #4432.

2022-06-27 00:13 UTC, Baezon requested changes
I wonder if an unconditional print for the successful creation and resolution of the waitAsync might be too much. I use a *lot* of waitAsync. Perhaps if it was an `nprintf` for the creation and successful resolution and `mprintf` for an invalid context?

2022-06-27 00:21 UTC, Goober5000 commented
I don't think so; I think in this situation all three should use mprintf.  If the user sees an aborted context via mprintf, he is going to want to see when it was created, and using nprintf for the creation would impose a barrier.

If the concern is log pollution, I think the focus should be on the lower-hanging fruit such as "entering warpout" and all the shader log messages.

2022-06-27 02:51 UTC, Baezon commented
I mean, yes, that is true, but the fact there are things which pollute the log *more* than this might, isn't related. The fact that the situation is bad isn't a reason to make it worse. It being an `nprintf` is a minor imposition in the case where it is the cause of a bug; it being an `mprintf` is a major imposition in all other cases, at least for me. Blighted has waitAsyncs happening as often as every few seconds in common scenarios over an hour or more play session, these prints will blow shader compilations out of the water. What about a default-on category? I would really just like some way to turn it off for myself.

2022-06-27 03:38 UTC, Goober5000 commented
Yeah, good point.

I could add a "scripting" category to nprintf, but I would like for it to default to "on", and I don't see a good way to do that.

2022-06-28 16:04 UTC, Goober5000 commented
Ok, take a look at the new commit.

2022-06-28 17:13 UTC, Baezon approved these changes

2022-06-28 17:55 UTC, merged