Allow multilock between traitors
scp-fs2open/fs2open.github.com pull request #4490
Opened 2022-07-13 01:25 UTC by JohnAFernandez

Use the proper attacking function here, as traitors need to be able to attack each other in dogfight mode.

2022-07-13 01:29 UTC, Goober5000 requested changes
Shouldn't this be `!attacks`?

2022-07-13 01:33 UTC, JohnAFernandez commented
Ah, thanks.  I forgot it was an early out.  I can't really test it at the moment, which is why it's in draft.

2022-07-13 05:04 UTC, Goober5000 approved these changes
Looks good, though a test before merge does make sense.

2022-07-14 02:15 UTC, JohnAFernandez commented
Closes #4493

2022-10-29 20:16 UTC, JohnAFernandez commented
Finally tested and confirmed fixed.

2022-10-29 20:16 UTC, merged