Scripting functions required for SCPUI conversion of Red Alert
scp-fs2open/fs2open.github.com pull request #4587
Opened 2022-08-24 00:40 UTC by MjnMixael

Should be everything required. Tested both committing to a mission and replaying the previous mission using these functions and it seems to work as expected.

2022-08-25 18:28 UTC, wookieejedi approved these changes
Particularly straight forward one. Looks good to me, and good to hear tests worked.

2022-08-26 03:01 UTC, Goober5000 requested changes
Due to the way FSO handles briefings, this will need a slight redesign.

2022-08-26 03:01 UTC, Goober5000 commented on code/scripting/api/objs/redalert.cpp
> +ADE_VIRTVAR(AudioFilename, l_RedAlertStage, nullptr, "The audio file of the stage", "red_alert_stage", "The  audio file")
"The  audio file" has an extra space

2022-08-26 16:53 UTC, MjnMixael commented on code/scripting/api/libs/ui.cpp
> +	return ade_set_args(L, "o", l_RedAlertStage.Set(Briefings[0]));
Hang on.. setting this as I think you intend causes a CTD when this method is called.

2022-08-26 17:14 UTC, MjnMixael commented on code/scripting/api/libs/ui.cpp
> +	return ade_set_args(L, "o", l_RedAlertStage.Set(Briefings[0]));
I think you mean `Briefings[0]`?

2022-08-27 17:41 UTC, Goober5000 commented on code/scripting/api/libs/ui.cpp
> +	return ade_set_args(L, "o", l_RedAlertStage.Set(Briefings[0]));
Yes, sorry, `Briefings` not `Briefing`.

2022-08-27 17:43 UTC, MjnMixael commented on code/scripting/api/libs/ui.cpp
> +	return ade_set_args(L, "o", l_RedAlertStage.Set(Briefings[0]));
In that case done

2022-08-27 17:47 UTC, MjnMixael commented
Feedback addressed

2022-08-27 17:54 UTC, Goober5000 reviewed
That `Briefing` discussion got me thinking.  Does SCPUI call any of the built-in ui functions, such as `red_alert_do_frame()`, or is the entire UI handled by the script?  Many of these use the `Briefing` pointer.  Or in the case of standard briefings, there are some functions that use it that aren't even part of the UI, such as `brief_compact_stages()`.

The `Briefing` pointer is initialized to null but is set to the briefing in use once the UI screen is initialized.  For example, in in `brief_init()`:
```
	// get a pointer to the appropriate briefing structure
	if(MULTI_TEAM){
		Briefing = &Briefings[Net_player->p_info.team];
	} else {
		Briefing = &Briefings[0];			
	}
```
And in `red_alert_init()`:
```
	if ( !Briefing ) {
		Briefing = &Briefings[0];			
	}
```
In summary, if your SCPUI script calls any FSO functions that use the `Briefing` pointer, then it will need to make sure the pointer is initialized when the briefing is.

2022-08-27 18:01 UTC, MjnMixael commented
None of this calls built-in functions (yet) and for data retrieval I try to avoid it.. though the Tech Room PR had to get a little fancier to initialize some of the data. Everything other than generating data is handled by the scripts before the game_state really gets through init.

2022-08-27 18:05 UTC, Goober5000 approved these changes
Ok.  In that case, everything looks good.

2022-08-28 17:18 UTC, merged