Implemented a command line flag that forces a fixed RNG seed,
scp-fs2open/fs2open.github.com pull request #4599
Opened 2022-08-28 17:42 UTC by EatThePath

Reseeds the rng every mission load, if not in MP.

In draft because I'm having compiler difficulties and haven't been able to test any.

2022-08-28 22:30 UTC, Goober5000 requested changes
Can we use a different term than "fixed"?  That's a word with multiple meanings.

You could save a variable by just testing that the seed is greater than zero.  On that note, your current code allows a seed of zero, which is disallowed according to the implementation of `Random::seed`.

2022-09-06 18:36 UTC, EatThePath commented
> Can we use a different term than "fixed"? That's a word with multiple meanings.

I assume the issue is potentional confusion with fix as in 'bugfix'? 

Fixed is the only term I can really think of being used regularly for this kind of thing. Do you have a preferred alternative? Everything else that comes to mind for me also has potential for confusion too.

2022-09-08 04:42 UTC, Goober5000 commented
Yeah, I was thinking about potential confusion with "bugfix".  It's hard to think of an alternative, but consulting a thesaurus:
* latched
* clamped
* locked
* pinned
* uniform

"Latched" has engineering heritage, while "pinned" has web heritage.

2022-09-12 14:05 UTC, Goober5000 approved these changes
👍

2022-09-15 13:30 UTC, merged