Improved beam, blob and warp lighting
scp-fs2open/fs2open.github.com pull request #4653
Opened 2022-09-14 18:17 UTC by qazwsxal

This was made in collaboration with @EatThePath, and focuses on improving the look of beams, weapons and warp lighting
This should be merged in after #4652 as it relies upon some of the changes made there.

Based off research by epic games, [Real Shading in Unreal Engine 4](https://cdn2.unrealengine.com/Resources/files/2013SiggraphPresentationsNotes-26915738.pdf), the tube and point light lighting calculations have been modified. 

Firstly, the point-source approximation used by beams/tube lights has been changed. Instead of choosing the nearest point of the tube light to the shaded fragment, the eye direction and surface normal are taken into account. This improves the look of the reflections of beams (especially on curved surfaces)

Secondly, all beam and point lights now have a sourceRadius. This slightly modifies the lighting calculation, nudging the position of the point-source-approximation so that the specular reflections appear to have a physical size. This prevents glossy reflections of point sources from diminishing into a single point and gives weapon lighting true "thickness" 

22.2.0
![22.2.0](https://cdn.discordapp.com/attachments/223511363807346691/990748063024963594/unknown.png)

With improved lighting
![improved](https://cdn.discordapp.com/attachments/223511363807346691/990738626881134612/unknown.png)

This also improves the look of subspace portal lighting:
(from joe's warmachine stream)
![joe's warmachine stream](https://cdn.discordapp.com/attachments/849709471273058324/1008437332782874755/unknown.png)

Pics from ETP's work:
![ETP1](https://cdn.discordapp.com/attachments/222801080621203456/996454241784840352/screen0561.png)
![ETP2](https://cdn.discordapp.com/attachments/222801080621203456/996453381143003156/screen0558.png)

2022-09-14 22:21 UTC, SamuelCho commented
great work! I always wanted to get some sort of area lights feature working after the PBR/HDR changes but hadn't had the time. thanks for putting some time into this.

2022-09-15 06:55 UTC, The-E requested changes

2022-09-15 06:55 UTC, The-E commented on code/starfield/starfield.cpp
> +					Warning(LOCATION, "Sun %s tried to set SunSpecularRGB. This feature has been deprecated and will be ignored.", sbm.filename);
I am not sure how often this is used, but I think this can be downgraded to a log print instead of a Warning

2022-09-15 17:40 UTC, The-E approved these changes

2022-09-15 18:07 UTC, merged