-luadev flag and lua log filter
scp-fs2open/fs2open.github.com pull request #4681
Opened 2022-09-19 23:07 UTC by EatThePath

Adds new default 'lua' filter category for all lua errors and output and -luadev flag that currently only makes lua errors non-fatal.

2022-09-19 23:08 UTC, EatThePath commented
Implements two points of #4665

2022-09-20 23:14 UTC, BMagnu requested changes
Mostly good.
Also, do I correctly understand this, that it will keep printing lua to the debug log without any special logging config?

2022-09-20 23:14 UTC, BMagnu commented on code/cmdline/cmdline.cpp
> +cmdline_parm luadev_arg("-luadev", "nullptr", AT_NONE);	// Cmdline_slow_frames_ok
That comment seems slightly outdated...

2022-09-21 01:25 UTC, EatThePath commented on code/cmdline/cmdline.cpp
> +cmdline_parm luadev_arg("-luadev", "nullptr", AT_NONE);	// Cmdline_slow_frames_ok
Whoops, I'll update that...

2022-09-21 01:25 UTC, EatThePath commented
> Mostly good. Also, do I correctly understand this, that it will keep printing lua to the debug log without any special logging config?

Yeah, I tested to make sure that it defaults to lua on if not specified.

2022-09-21 07:44 UTC, BMagnu approved these changes

2022-09-21 20:31 UTC, merged