Add AI flag to support ai bay arrivals > 10 seconds
scp-fs2open/fs2open.github.com pull request #4733
Opened 2022-09-30 14:40 UTC by wookieejedi

Currently, if an AI ship is emerging from a bay path, the AI will stop following that path after only 10 seconds (and some distance away from the starting point). This results in AI breaking off a path early if a bay arrival path is long and/or uses a slow bay arrive multipliers. For bays that require the ship to follow the exact path this results in AI that then run into the parent ship and each other.

This PR adds a flag which disables that 10 second timeout. Also, in my tests having a flag to disable works best, as opposed to setting a max time (which is hard to calculate with varying ship speeds and varying bay path lengths).

PR is tested and works as expected.

2022-09-30 23:23 UTC, Goober5000 requested changes

2022-09-30 23:23 UTC, Goober5000 commented on code/ai/ai_profiles.cpp
> +				set_flag(profile, "$bay arrivials not time limited:", AI::Profile_Flags::Disable_bay_emerge_timeout);
"arrivials"

2022-09-30 23:49 UTC, wookieejedi commented on code/ai/ai_profiles.cpp
> +				set_flag(profile, "$bay arrivials not time limited:", AI::Profile_Flags::Disable_bay_emerge_timeout);
thanks, just fixed!

2022-10-01 00:37 UTC, Goober5000 approved these changes

2022-10-01 16:39 UTC, merged