When rendering stuff outside of ON OBJECT RENDER hooks, use immediate mode
scp-fs2open/fs2open.github.com pull request #4735
Opened 2022-09-30 16:00 UTC by The-E

2022-09-30 16:05 UTC, EatThePath approved these changes
Looks solid, restores old behavior from before #4664 when not in the object render hook, and resolves a regression stemming from that change.

I think it could benefit from a sprinkle of explanatory comments for future tinkerers, but I wouldn't make that a blocking request

2022-09-30 16:44 UTC, EatThePath approved these changes
comments look good

2022-09-30 16:58 UTC, Goober5000 requested changes
The same fix should be applied to `drawModelOOR`, immediately below it, since these are twin functions.

Also, if these two script functions are really intended to be used outside On Object Render, and we intend to support that functionality, then the function header comments should be updated.

2022-09-30 17:18 UTC, The-E commented
> The same fix should be applied to `drawModelOOR`, immediately below it, since these are twin functions.
> 
> Also, if these two script functions are really intended to be used outside On Object Render, and we intend to support that functionality, then the function header comments should be updated.

Done

2022-09-30 17:32 UTC, Goober5000 commented
Good, but regarding the documentation - if our intent is that scripters can use this anywhere, then the "Use with extreme care" sentence should be removed from both functions' headers.

2022-10-01 08:50 UTC, The-E commented
> Good, but regarding the documentation - if our intent is that scripters can use this anywhere, then the "Use with extreme care" sentence should be removed from both functions' headers.

done

2022-10-01 19:22 UTC, Goober5000 approved these changes
Looks good now, although the previous multi-string single-arg description was turned into a multi-arg description

2022-10-01 19:23 UTC, Goober5000 commented on code/scripting/api/libs/graphics.cpp
> +	     "Note: this method does NOT use CurrentResizeMode.",
```suggestion
         "Draws the given model with the specified position and orientation.  "
	     "Note: this method does NOT use CurrentResizeMode.",
```

2022-10-01 20:06 UTC, merged