Update `$POF file Techroom:` Usage
scp-fs2open/fs2open.github.com pull request #4785
Opened 2022-10-14 15:13 UTC by wookieejedi

Currently `$POF file Techroom:` is only used in the weapons loadout screen (despite having techroom in the name). This PR expands the use of the `$POF file Techroom:` to shiploadout select and the actual techroom.

If it is desired, I can put it behind a game settings flag, but IMO it would make the most sense for modders to have this just work as the actual name implies.

Tested and works as expected.

2022-10-14 15:20 UTC, BMagnu commented
I concur on not making that a flag and just enabling it for the techroom and stuff

2022-10-15 00:54 UTC, Goober5000 requested changes
While this looks fine, considering the number of times the same code appears, how about putting it in a function with a header like this:
```
int model_load(ship_info *sip, bool prefer_tech_model)
```

2022-10-15 02:55 UTC, wookieejedi commented
> , bool prefer_tech_model

Good idea, update pushed.

2022-10-15 03:01 UTC, Goober5000 approved these changes

2022-10-16 01:12 UTC, merged