Fix crash on `ai_goal_purge_invalid_goals`
scp-fs2open/fs2open.github.com pull request #4906
Opened 2022-11-16 23:18 UTC by wookieejedi

`ai_goal_purge_invalid_goals` was previosuly provided with all wings in a mission, even if the wing was not present, which resulted in a CTD. This fixes (#4899). Tested and works as expected.

2022-11-16 23:19 UTC, JohnAFernandez requested changes

2022-11-16 23:19 UTC, JohnAFernandez commented on code/ai/aigoals.cpp
> +			ai_goal_purge_invalid_goals(aigp, Wings[i].ai_goals, NULL, i);
nullptr

2022-11-16 23:22 UTC, wookieejedi commented on code/ai/aigoals.cpp
> +			ai_goal_purge_invalid_goals(aigp, Wings[i].ai_goals, NULL, i);
whoops, changed

2022-11-16 23:23 UTC, Goober5000 requested changes
This fixes the crash, but I don't think it is quite the right fix with regards to the AI code.  Let me noodle over this a bit.

2022-11-16 23:31 UTC, JohnAFernandez approved these changes

2022-11-16 23:56 UTC, MageKing17 approved these changes
Since the code above won't purge goals from ships that aren't present, it seems consistent to also skip wings that aren't present.

2022-11-17 00:14 UTC, Goober5000 commented
The problem is that wings can be absent for a time and then reappear.

2022-11-17 00:25 UTC, MageKing17 commented
Ships can also arrive mid-mission; what's your point?

2022-11-17 00:29 UTC, Goober5000 commented
But not the *same* ship.  By contrast, the *same* wing can reappear.

Anyway I found what I was looking for.  The fundamental solution is correct, it's just a question of where to put it.  I recommend moving the change to `ai_goal_purge_invalid_goals` as follows:
```
                    // for wings that are present we grab the ship type of one of the ships in the wing
                    if (ai_wingnum >= 0 && Wings[ai_wingnum].current_count > 0) {
```

2022-11-17 04:58 UTC, Goober5000 commented
Closing in favor of #4908

2022-11-17 04:58 UTC, closed without merging