Generalize linear interpolation
scp-fs2open/fs2open.github.com pull request #5003
Opened 2022-12-14 00:01 UTC by JohnAFernandez

This creates a (very small) api for linear interpolation between two recorded positions, velocitites, and desired velocities and moves multiplayer over to that system.  Now that it is generalized, other games systems (esp. weapons fire) can now use this code to set an object's position to what it would be between frames.

2024-01-17 04:34 UTC, JohnAFernandez commented
I was finally able to run a test for this now that I have a better dev machine.  Interpolation works just like in the old system, so I'm marking as ready for review.  This is a stepping stone to getting primary fire rates higher than the frame rate.

2024-02-05 23:55 UTC, JohnAFernandez commented
This really needs to get in before 24.2, otherwise higher weapon fire rate than framerate is literally not going to happen.

2024-06-17 10:28 UTC, BMagnu requested changes
A very tiny constness thing, but this looks good and clean.

2024-06-17 10:28 UTC, BMagnu commented on code/object/object.cpp
> +void physics_populate_snapshot(physics_snapshot& snapshot, object* objp)
Ideally, this takes a const pointer.

2024-06-17 12:34 UTC, JohnAFernandez commented on code/object/object.cpp
> +void physics_populate_snapshot(physics_snapshot& snapshot, object* objp)
```suggestion
void physics_populate_snapshot(physics_snapshot& snapshot, const object* objp)
```

2024-06-17 12:46 UTC, JohnAFernandez commented on code/object/object.h
> +void physics_populate_snapshot(physics_snapshot& snapshot, object* objp);
```suggestion
void physics_populate_snapshot(physics_snapshot& snapshot, const object* objp);
```

2024-06-18 18:09 UTC, BMagnu approved these changes

2024-06-18 18:10 UTC, merged