fictionviewer localization
scp-fs2open/fs2open.github.com pull request #5012
Opened 2022-12-15 20:09 UTC by MjnMixael

Implements true fiction viewer localization. If language setting is not English then it will try to find the fiction viewer file with the language extension applied. If the file specified is `somefile.txt` then it will search for `somefile-gr.txt`, for example, if the language setting is German. If that file is not found then it will default to the base filename `somefile.txt`.

Also updates the scpui virtvar with the same code.

Fixes #1836 for real this time

2023-02-11 14:50 UTC, BMagnu approved these changes

2023-02-12 01:23 UTC, Goober5000 requested changes

2023-02-12 01:23 UTC, Goober5000 commented on code/scripting/api/objs/fictionviewer.cpp
> +	return ade_set_args(L, "s", localized_filename);
I think this line needs a `.c_str()`

2023-02-12 14:27 UTC, MjnMixael commented on code/scripting/api/objs/fictionviewer.cpp
> +	return ade_set_args(L, "s", localized_filename);
Yes it does

2023-02-12 17:54 UTC, Goober5000 approved these changes

2023-02-14 08:26 UTC, merged