add should-be-dead checks for object iterations
scp-fs2open/fs2open.github.com pull request #5050
Opened 2022-12-27 05:13 UTC by Goober5000

Follow-up to #5040.  This extends the checks to most iterations over `obj_used_list` in FSO.  There are a few exceptions such as `waypoint_add` and `waypoint_remove`, plus a few others.  And none of the object iterations in FRED have the guard because FRED does not use the same object life cycle as FSO.

2022-12-31 00:38 UTC, JohnAFernandez requested changes

2022-12-31 01:16 UTC, Goober5000 commented on code/object/object.cpp
> +		if ( objp != Player_obj && !objp->flags[Object::Object_Flags::Should_be_dead] ) {
Okay

2022-12-31 01:16 UTC, Goober5000 commented on code/network/multiteamselect.cpp
> -	int idx,team_index,slot_index,found,player_count,shipnum;
Okay

2023-01-01 00:28 UTC, JohnAFernandez approved these changes

2023-01-01 04:23 UTC, JohnAFernandez commented
Merging, as this may fix an issue encountered by the BtA team.

2023-01-01 04:23 UTC, merged