make sure game time is running in the mainhall
scp-fs2open/fs2open.github.com pull request #5060
Opened 2022-12-29 17:04 UTC by MjnMixael

Fixes #4755 by making sure the timer is not ever paused during a mainhall game state. We can't rely on UI-specific code to restart the timer after mission load if SCPUI is being used, so it should be done whenever the mainhall is entered probably. I didn't do a deep dive into the timer functions, so maybe there's a more appropriate fix elsewhere.

2022-12-29 17:19 UTC, Goober5000 commented
I'll take a look at this.  The timer code can be dicey, so I want to look at some of the possible code flow paths.

2023-01-03 07:42 UTC, Goober5000 commented
#4755 is going to need a more comprehensive fix.  I've posted a comment there.

2023-01-03 14:40 UTC, MjnMixael commented
> #4755 is going to need a more comprehensive fix. I've posted a comment there.

Not that comprehensive. Just give SCPUI the ability to call the level close method. Tested and works.

2023-01-03 18:09 UTC, Goober5000 commented
Hang on... I ran a search just now for `game_level_close()` and there is already a `mn.unloadMission()` function.  I missed this earlier because I searched for `freespace_stop_mission()`.

2023-01-03 20:01 UTC, MjnMixael commented
> mn.unloadMission()

That method does not work presumably because SCPUI doesn't pass the `if(Game_mode & GM_IN_MISSION)` test

2023-01-03 20:55 UTC, MjnMixael commented
can't wait to see why this fix won't work either

2023-01-04 01:03 UTC, Goober5000 requested changes
Looks good.  Only thing is that the documentation should reflect that the parameter is optional.

2023-01-04 01:03 UTC, Goober5000 commented on code/scripting/api/libs/mission.cpp
> +ADE_FUNC(unloadMission, l_Mission, "boolean forceUnload", "Stops the current mission and unloads it. If forceUnload is true "
```suggestion
ADE_FUNC(unloadMission, l_Mission, "[boolean forceUnload]", "Stops the current mission and unloads it. If forceUnload is true "
```

2023-01-04 01:57 UTC, MjnMixael commented on code/scripting/api/libs/mission.cpp
> +ADE_FUNC(unloadMission, l_Mission, "boolean forceUnload", "Stops the current mission and unloads it. If forceUnload is true "
Done

2023-01-04 02:05 UTC, Goober5000 approved these changes

2023-01-04 02:08 UTC, JohnAFernandez approved these changes

2023-01-04 02:23 UTC, merged