This case was never ported to qtFRED
scp-fs2open/fs2open.github.com pull request #5082
Opened 2023-01-05 17:05 UTC by MjnMixael

2023-01-05 17:09 UTC, JohnAFernandez approved these changes

2023-01-05 18:27 UTC, tomimaki commented on qtfred/src/ui/widgets/sexp_tree.cpp
> +	case OPF_TRANSLATING_SUBSYTEM:
Subsytem is typo or intended?

2023-01-05 18:29 UTC, MjnMixael commented on qtfred/src/ui/widgets/sexp_tree.cpp
> +	case OPF_TRANSLATING_SUBSYTEM:
Typo. Good catch.

2023-01-06 02:25 UTC, Goober5000 requested changes
Great catch.

Looking at `get_listing_opf_subsystem`, there are a few additional edits, related to `OPS_TRANSLATE`, that are needed in order to fully sync the two files.

2023-01-06 18:35 UTC, Goober5000 requested changes
Almost done.  The `OPS_TRANSLATE` definition needs to be added to the `// specific types of subsystems we're looking for` list, in the same order as in FRED's sexp_tree.cpp.

2023-01-06 18:43 UTC, MjnMixael commented
> Almost done. The `OPS_TRANSLATE` definition needs to be added to the `// specific types of subsystems we're looking for` list, in the same order as in FRED's sexp_tree.cpp.

yeah ok. I'm kinda done cleaning up the qtFRED mess. Feel free to edit this PR as you like. I have neither the time or motivation to keep chasing this one in circles and I was told recently that's all the reason I need not to do stuff.

2023-01-07 08:05 UTC, MjnMixael commented
OK fine. Last one because I found another thing missing.

2023-01-07 21:36 UTC, Goober5000 approved these changes

2023-01-08 18:32 UTC, merged