Optimizing the trail renderer by avoidng repeated batch_find calls
scp-fs2open/fs2open.github.com pull request #5154
Opened 2023-01-29 23:17 UTC by EatThePath

Building large trails is an annoyingly costly process in terms of frame times. This makes it a very little bit cheaper. Not a big enough optimization to have very visible effects, but one I think is worth doing.

2023-01-29 23:19 UTC, Baezon commented
A different idea of doing the same thing that is more extensible: what if the batching code simply had a global of the last-used texture id and batch, and if the same texture id is used, use the last used batch as well, since that's what the batch is based on right?

2023-01-29 23:59 UTC, EatThePath commented
> A different idea of doing the same thing that is a little more extensible: what if the batching code simply had a global of the last-used texture id and batch, and if the same texture id is used, use the last used batch as well, since that's what the batch is based on right?

That would probably work, and it'd probably be faster than the status quo, but it would still be a test and possible branch executed on each segment of every trail. Maybe it'd optimize away, but I wouldn't trust it to be quite as fast.

Still, might be worth doing for general batch streamlining. It'd need to check the batch info as well as the texture info, I think.

2023-01-30 00:45 UTC, JohnAFernandez requested changes

2023-01-30 00:45 UTC, JohnAFernandez commented on code/render/batching.cpp
> +		Int3();
We have `verify()` and `verification()` that can be used to replace `int3()`.

2023-04-17 21:13 UTC, JohnAFernandez approved these changes

2023-04-17 21:16 UTC, merged