make the vulkan support buildable again
scp-fs2open/fs2open.github.com pull request #5160
Opened 2023-02-01 09:36 UTC by The-E

we are currently shipping an old copy of `vulkan-hpp`, which has since been rolled into the official vulkan sdk. This PR removes that library, and refactors our existing code to use the base sdk version instead.

Note that this doesn't improve functionality. Vulkan rendering is still not working right now.

2023-02-01 09:37 UTC, The-E commented
This addresses #4840

2023-02-01 13:54 UTC, The-E commented
*sigh*
of course, in my wisdom I forgot to add functionality to cmake to download the vulkan sdk....

2023-02-20 09:12 UTC, BMagnu requested changes

2023-02-20 09:12 UTC, BMagnu commented on freespace2/SDLGraphicsOperations.cpp
> +		ImGui_ImplSDL2_Shutdown();
In the manager you run the SDL2 Frame in Vulkan mode, but here you don't do the shutdown in Vulkan mode.
These should likely be symmetric, so either don't do the SDL2 Frame in Vulkan mode, or (more likely AFAICT) do the SDL2 shutdown in vulkan mode as well

2023-02-20 09:28 UTC, BMagnu approved these changes

2023-02-20 09:54 UTC, merged