Add `GetVertex()` and `NumVertices()` script functions and clean up random submodel point retrieval a bit
scp-fs2open/fs2open.github.com pull request #5199
Opened 2023-02-18 04:36 UTC by Baezon

`GetVertex` allows for retrieval of specific vertices or random ones, and with `NumVertices()` a scripter could even do some advanced 'model parsing' type operations if they were feeling spicy, but random retrieval was my main goal.

Additionally, cleans up `submodel_get_two_random_points_better` a bit, there's no real reason for this function to get two points at a time, even if that's a common case, resulting in awkward scenarios where callers need to declare useless temporaries when they only need one. Instead it should return a single vertex, and you can call it more than once if you need more (and for what it's worth, the Shivan Comm Node *does* have a collision tree).

2023-02-18 17:40 UTC, The-E requested changes
One small change, then it should be good

2023-02-18 17:40 UTC, The-E commented on code/model/modelinterp.cpp
>  			nprintf(("Model", "In submodel_get_two_random_points_better(), model %s does not have a collision tree!  Falling back to submodel_get_two_random_points().\n", pm->filename));
a) I have never, ever seen this print
b) the function name referenced here should be updated to reflect the actual function throwing this warning

2023-02-18 18:56 UTC, Goober5000 commented
> (and for what it's worth, the Shivan Comm Node does have a collision tree).

The Shivan Comm Node most certainly *did not* have a collision tree when I tested it.  Did you test both the retail and MVP versions of the model?

Anyway, that's the entire reason for that if() block; the function crashed before I added it.

2023-02-18 20:00 UTC, Baezon commented
The MVPs comm node indeed does not... I had assumed it was a volition comment, actually. I didn't think not having a collision tree was even possible, and `submodel_get_random_point_fallback` doesn't even return correct vertex positions. I've updated the PR, but I'm investigating this further...

2023-02-18 20:38 UTC, Baezon commented
Opened #5208, to fix the lack of a collision tree sometimes. With that PR, all models can be asserted to have collision trees. (The vertex positions were fine btw, the mvps comm node is just set up a bit differently)

2023-02-18 20:48 UTC, Goober5000 commented
Ah, nice

2023-02-19 07:57 UTC, The-E approved these changes

2023-02-19 07:58 UTC, merged