Check duplicate enum items
scp-fs2open/fs2open.github.com pull request #5213
Opened 2023-02-21 15:14 UTC by MjnMixael

Review of #5036 suggested to me that we should be checked for duplicate enum items here, too.

2023-02-21 15:21 UTC, BMagnu approved these changes

2023-02-21 17:39 UTC, Goober5000 requested changes

2023-02-21 17:39 UTC, Goober5000 commented on code/parse/sexp/LuaSEXP.cpp
> +						continue;
This will continue the inner loop, not the outer loop, and thus it won't skip adding the duplicate enum item to the list.

2023-02-21 17:39 UTC, Goober5000 commented on code/parse/sexp/LuaSEXP.cpp
> +					if (!stricmp(item.c_str(), thisList.list[i].c_str())) {
This can use `SCP_string_lcase_less_than()(item, thisList.list[i])`

2023-02-21 17:39 UTC, Goober5000 commented on code/parse/sexp/sexp_lookup.cpp
> +					// Case insensitive check if the item already exists in the list
Same comments apply here

2023-02-22 00:22 UTC, Goober5000 approved these changes

2023-02-23 13:32 UTC, merged