Localized Volumetric Nebulae
scp-fs2open/fs2open.github.com pull request #5231
Opened 2023-03-04 22:43 UTC by BMagnu

This PR adds the ability to use (as of now) up to one area containing arbitrary localized nebulae:

https://user-images.githubusercontent.com/6238428/222931394-323a3716-9c9d-4b16-a039-3eee292bbc2b.mp4

Closes #4193

The base rendering technique is adapted from Andrew Schneider's 2015 SIGGRAPH talk "The real-time volumetric cloudscapes of Horizon: Zero Dawn". It allows specifying a POF as the hull of a nebula, which will be rendered using ray marching. The POF itself however must be watertight, and it must not have any overlapping polygons. Having one mesh enclosed within another without any touching polygons will create a region of space within the nebula which is "empty" and not nebulized. Furthermore, many options for look and feel are possible and can be used. The performance is acceptable, but not perfect and subject to further optimization.

The following is a list of improvements I can see to be made in the future.

- Enhance the main Nebula texture to also contain an SDF for the regions of empty space. Since the nebula does not need 256 different density values, the lower half of the alpha component of the nebula color could be used to signal empty space with an according value for the SDF, while the upper half could indicate occupied space with the desired level of density. This would allow both optimization with regards to unnecessary samples in empty space and could drastically speed up sparse nebulae, as well as allowing a path to proper noise-based edge eroding.
- An Editor in FRED to allow changing the nebulas property in FRED, as well as a wireframe renderer for the volumetric nebula itself within the mission.
- Calculation of the nebulae's texture's voxels not from a solid tabled color, but from the texture of the nebula, allowing for more varied colorscapes.
- Allow multiple nebulae regions per render pass / mission.
- Allow poofs to spawn within localized nebulae.
- Allow a player that is "sufficiently inside" a localized nebula to have the localized nebula fade into a fullneb and back once they leave.

2023-03-05 15:00 UTC, The-E requested changes

2023-03-06 11:39 UTC, The-E commented on code/nebula/volumetrics.cpp
> +	//This expects that the constructor was called in an if(optional_string("Volumetrics")) or something
IMHO, if I invoke a constructor, I do not expect that constructor to require a) the text parser to be initialized, b) the parser being set to parse a mission file, c) the parser to be at exactly the point in the mission file where the data it reads is expected to be. On a technical level, sure, this is all possible and adding a separate `parse_volumetric_nebula` method doesn't make that much of a difference, but to me this sort of quasi-hidden dependency screams "footgun".

2023-03-06 13:01 UTC, BMagnu commented on code/nebula/volumetrics.cpp
> +	//This expects that the constructor was called in an if(optional_string("Volumetrics")) or something
Fair point. I'll pack it into a parsing method of the ``volumetric_nebula`` class, with some additional asserts in the render method that the object is sufficiently initialized.

2023-03-06 13:43 UTC, The-E approved these changes

2023-03-06 15:38 UTC, merged