Allow 0-Asteroid setups
scp-fs2open/fs2open.github.com pull request #5329
Opened 2023-04-12 18:09 UTC by BMagnu

Implements part of #5255.
This allows for an asteroid table to be functionally empty, not requiring any asteroids to be set up.
Evidently, this will disallow the usage of asteroid fields, but some TC's may not need any, so allow these to set up without asteroids.

2023-04-12 20:08 UTC, Baezon commented
I'm surprised this is all it takes! What exactly does it say in FRED if you try to add one? What if you use `set-asteroid-field`?

2023-04-15 14:52 UTC, MjnMixael commented
I think FRED will just complain that you have to select an asteroid if you try to create a field and click OK. The asteroid lists will be empty which is allowable in MFC.

For the sexps (set-asteroid-field and set-debris-field), it should be checked that the list builder doesn't crash FRED. I can't recall if those get 'none' appended or not.

2023-04-15 15:05 UTC, MjnMixael requested changes
I checked. The debris sexp gets 'none' applied so it should be fine and the asteroid sexp doesn't list the 'roids'.

2023-04-15 15:24 UTC, MjnMixael approved these changes

2023-04-15 23:39 UTC, merged