Randomize particle rotation
scp-fs2open/fs2open.github.com pull request #5335
Opened 2023-04-14 19:24 UTC by Baezon

Still leaves room for more in-depth options later, but for now just a global flag. Also removes `particle_index` dunno wtf 'dynamic array usage' is about but it was used before for a janky random 90 degree rotation (which was also broken a few years ago)

2023-04-14 20:36 UTC, wookieejedi approved these changes
Tests work well and overall LGTM

2023-04-15 18:54 UTC, Goober5000 requested changes

2023-04-15 18:54 UTC, Goober5000 commented on code/mod_table/mod_table.cpp
> +bool Randomize_particle_rotation;
`Randomize_particle_rotation` should be initialized in `mod_table_reset`

2023-04-15 21:23 UTC, Goober5000 approved these changes

2023-04-17 11:37 UTC, merged