Animation Drivers
scp-fs2open/fs2open.github.com pull request #5451
Opened 2023-06-07 10:32 UTC by BMagnu

Current proposal for integration of advanced animation drivers.
They will notably allow three main new features:
1. Time remapping: Instead of having animations be a function of movement over time, you can now remap animations to be a function of movement over an arbitrary value source (like the speed of a ship, or the value of ETS). It is also possible to modify the value with a curve before using it as the animation source. Do note that in this case, The animation tables value for "time" are now no longer in seconds, but in whatever unit the value chosen is. Also, be aware that most animation flags will no longer apply when not used with actual time.
2. Value driving: It is possible to link a property of an animation, like it's speed, to a curve-modified value source. This allows for example for animations whose speed is proportional to the forward velocity of a ship.
3. Initial value driving: Similar to 2, it is also possible to evaluate these driver chains only once when the animation first starts. One of the interesting use cases for this is setting an initial value for time, which would allow stuff like random initial time which is identical for all animations on one ship.

It accomplishes this by refactoring how animations are handled. Instead of having their direction integrated into their state, it's now a separate instance property. The state is thus reduced to Running, Paused, and Untriggered.

This is still untested and thus in draft. This feature is not intended for 23.2.

2023-12-05 20:16 UTC, Baezon requested changes
Frankly, this is mostly beyond me, but this did jump out at me.

2023-12-05 20:25 UTC, BMagnu commented on code/model/animation/modelanimation.cpp
> +					curve = Curves[curve_get_by_name(curve_name)];
Good catch!

2023-12-05 20:35 UTC, Baezon approved these changes

2023-12-07 23:37 UTC, TRBlount approved these changes

2023-12-09 01:58 UTC, merged