Ignore voice recognition events while game is paused.
scp-fs2open/fs2open.github.com pull request #5492
Opened 2023-07-12 22:29 UTC by MageKing17

If you pause the game, say something into the microphone, then unpause, it can abruptly perform an action based on voice recognition; this is probably counter to player expectations. This adds a `gameseq_get_state() != GS_STATE_GAME_PAUSED` check to the existing conditional.

2023-07-12 22:36 UTC, Goober5000 requested changes
Good catch.  I think this should also check `popup_active()` because pressing Escape mid-mission technically doesn't count as pausing.

2023-07-12 22:37 UTC, Goober5000 requested changes
Good catch.  I think this should also check `popup_active()` because pressing Escape mid-mission technically doesn't count as pausing.

2023-07-12 23:08 UTC, MageKing17 commented
Threw in a `popupdead_is_active()` check as well, because regular controls also stop being processed while that's true.

2023-07-13 00:09 UTC, Goober5000 approved these changes
I think `popup_active()` encompasses `popupdead_is_active()`, but even if it's redundant it should be fine.

2023-07-13 00:10 UTC, MageKing17 commented
> I think `popup_active()` encompasses `popupdead_is_active()`, but even if it's redundant it should be fine.

It does not; `popupdead_is_active()` sidesteps the normal popup code, so `popup_active()` will return false when it returns true.

2023-07-13 00:13 UTC, Goober5000 commented
OIC.  Ok then.

2023-07-16 22:47 UTC, merged