Make `lock_fov` settable for missiles.
scp-fs2open/fs2open.github.com pull request #5493
Opened 2023-07-12 23:13 UTC by MageKing17

The code has always checked a per-weapon-class value called `lock_fov` when comparing the dot product of a ship to its target (or a homing missile to a potential new target) to see if it can lock on to it, however the weapon table hasn't ever included a way to set this value; it's always the default value of 0.85. This just adds "+Lock FOV:" entries to homing missile parsing after "+Seeker Strength:", which will set `lock_fov` as long as the supplied input is between -1 and 1.

(Note to self: don't forget to update the wiki whenever this gets merged.)

2023-07-12 23:24 UTC, Baezon requested changes
Excellent idea, I was always surprised to see that `lock_fov` was hardcoded, although I never needed to change it myself before.

This should however do some conversion and expose the value to modders as degrees isntead of a dot product to match similar angle-based options.

2023-07-12 23:25 UTC, Goober5000 requested changes
As a user-friendliness enhancement, methinks `lock_fov` should be specified in the table in degrees, then computed on parse.

2023-07-12 23:25 UTC, Goober5000 commented on code/weapon/weapons.cpp
> +					error_display(0, "Lock FOV values with a magnitude higher than 1 make no sense; ignoring value of %d for missile \'%s\'.", temp, wip->name);
The `%d` should be `%f`

2023-07-12 23:25 UTC, Goober5000 commented on code/weapon/weapons.cpp
> +					error_display(0, "Lock FOV values with a magnitude higher than 1 make no sense; ignoring value of %d for missile \'%s\'.", temp, wip->name);
Here too

2023-07-12 23:26 UTC, Baezon commented
You owe me a soda

2023-07-12 23:28 UTC, MageKing17 commented
> This should however do some conversion and expose the value to modders as degrees instead of a dot product to match similar angle-based options.

Can you name an example of such a "similar angle-based option"?

2023-07-12 23:33 UTC, Baezon commented
Basically any time angles are needed. Missile view cone, and turret fovs are ones that come to mind that specifically turn them into dot products, but table degrees to internal radians (although not explicitly the case here) is even more common which you can find many examples of just by searching `fl_radians` in table parsing areas.

2023-07-12 23:54 UTC, MageKing17 commented
I saw `+View Cone:` almost immediately after I posted that; I also realized that I misread the code and `fov` is used for homing weapons looking for a new target; `lock_fov` is solely used by aspect/javelin missiles, so I'll be correcting both of those issues.

2023-07-12 23:59 UTC, Baezon approved these changes

2023-07-13 00:07 UTC, Goober5000 reviewed
One more question.  Is cutting the angle in half correct here?

2023-07-13 00:09 UTC, MageKing17 commented
> One more question. Is cutting the angle in half correct here?

Yes; otherwise, we're only measuring half of the field of view (center to side instead of side to side).

2023-07-13 00:13 UTC, Baezon commented
Tmk, various fields waffle on center-to-edge vs edge-to-edge, so it's fine as long as it's clear to the user which it is.

2023-07-13 00:14 UTC, Goober5000 approved these changes

2023-07-13 00:48 UTC, MageKing17 commented
Other FOV fields that get converted to a normalized dot product (like the aforementioned "+View Cone:", but also "$Turret Base FOV:" or "$Turret Barrel FOV:") also divide the input in half, so this is (AFAICT) the most consistent way to do it.

2023-10-24 11:26 UTC, merged