Fix a few typos
scp-fs2open/fs2open.github.com pull request #5598
Opened 2023-09-14 13:34 UTC by twolife

Reported by Lintian when packaging the engine for Debian; it shouldn't hurt

2023-09-14 16:06 UTC, Goober5000 requested changes
A lot of changes, but they all look good.  Just one small tweak needed.

2023-09-14 16:06 UTC, Goober5000 commented on fred2/campaigntreeview.cpp
> +	// draw level separator
This should be plural
```suggestion
	// draw level separators
```

2023-09-15 07:18 UTC, twolife commented on fred2/campaigntreeview.cpp
> +	// draw level separator
Ooops, good catch :-)

2023-09-15 07:23 UTC, Goober5000 approved these changes

2023-10-20 18:29 UTC, Goober5000 commented
@twolife We're ready to merge this, but one of the files now has conflicts due to the addition of some XSTRs.  Could you updaate the PR?

2023-10-25 00:33 UTC, merged