Fix null dereference when a subsystem is hit for damage by a null object
scp-fs2open/fs2open.github.com pull request #5642
Opened 2023-09-30 07:58 UTC by BMagnu

I'm not exactly 100% sure what causes this specific situation, but looking at the function, it seems that getting a null object as the other hit object is allowed.
This fixes the damage carry check, and since not carrying the damage will happen with all non-shockwaves, it'll also happen with null objects. The check in L 958 is safe btw, since weapon_info_index is guaranteed to be -1 for a null other_obj (in fact, checks further up in the function already rely on that)

2023-09-30 08:13 UTC, Baezon approved these changes
Fwiw, this is explicitly the case for the `explosion-effect` sexp, not sure if any others though.

2023-09-30 17:54 UTC, Goober5000 requested changes
There is another potential null dereference a few lines further down:
```
// Nuke: this will finally factor it in to damage_to_apply and i wont need to factor it in anywhere after this
damage_to_apply = Armor_types[subsystem->armor_type_idx].GetDamage(damage_to_apply, dmg_type_idx, ss_dif_scale, other_obj->type == OBJ_BEAM);
```

Optional suggestion: consider making a few `other_object_is_X` boolean variables, à la `ship_do_damage`.  This would make object checks a little cleaner throughout `do_subobj_hit_stuff`.

2023-10-01 15:29 UTC, Goober5000 requested changes

2023-10-01 15:29 UTC, Goober5000 commented on code/ship/shiphit.cpp
> +				if (other_obj_is_shockwave || (!(subsystem->system_info->flags[Model::Subsystem_Flags::Carry_shockwave]))) {
This should be `!other_obj_is_shockwave`

Optional: remove the outer pair of parentheses from the second half of the condition to make it more readable

2023-10-01 15:29 UTC, Goober5000 commented on code/ship/shiphit.cpp
> +	if (other_obj_is_shockwave)	// Goober5000 check for NULL
You could remove the `// Goober5000 check for NULL` part of this line since the null check is now done earlier.

2023-10-03 00:20 UTC, merged