Add child enum suffix option
scp-fs2open/fs2open.github.com pull request #5798
Opened 2023-11-13 17:15 UTC by MjnMixael

This feature adds, hopefully, the final level of arbitrary do-whatever-you-want-ness to lua sexps. The existing `child_enum` parameter type takes whatever the parent parameter's text is and looks for a Lua Enum list with that name. It was originally intended to be able to have the parent be a Lua Enum list of Lua Enum lists. But I realized it can be whatever you want, currently. The parent could a `ship` type and then the game would look for a Lua Enum list with the name of the ship. That's handy, but it's a one-off. You can only have one list with that name.

This allows a `child_enum` to optionally specify a list name suffix. So if the parent parameter is a ship, the child_enum can specify to look for a Lua Enum list that's `shipname + suffix`.

This also downgrades an Error to a log print. If the code can't find the specified enum list we don't have to hard stop. We can just return `<none>` and move on.

2023-11-15 22:30 UTC, JohnAFernandez commented on code/parse/sexp.cpp
> +	for (int i = 0; i < (int)Dynamic_enum_suffixes.size(); i++) {
Cast

2023-11-15 22:34 UTC, JohnAFernandez requested changes
Looks like just that one thing.  At least as far as I can tell.  Sexp code is not my specialty, but on the other hand, it's less than 50 lines.

2023-11-15 22:35 UTC, MjnMixael commented on code/parse/sexp.cpp
> +	for (int i = 0; i < (int)Dynamic_enum_suffixes.size(); i++) {
Changed to size_t

2023-11-15 22:36 UTC, JohnAFernandez approved these changes

2023-11-17 16:26 UTC, wookieejedi commented
Will plan to merge later today

2023-11-18 02:45 UTC, merged