avoid storing ship_info pointers in data structures
scp-fs2open/fs2open.github.com pull request #5800
Opened 2023-11-13 17:53 UTC by Goober5000

For collections that we want to make dynamic, we should not store pointers in data structures because these pointers will be invalidated if the collection is resized.  This PR takes care of all `ship_info` pointers stored in data structures in the codebase.

Since `WarpEffect` stored pointers to objects and ships (and warp params, which is already dynamic), this PR handles those as well.  There are, of course, more places where ship and object pointers are stored that will eventually need to be handled.

2023-11-14 21:06 UTC, JohnAFernandez requested changes
One quick thing

2023-11-14 21:10 UTC, Baezon commented
I was actually thinking about recently changing some `weapon_info_index` fields into just `weapon_info*`. *Technically*, being in a vector they are "dynamic", but morally, they aren't. We parse them once, and then the vector is never changed again, so theoretically pointers should still be valid? While parsing perhaps, the vector may be changing size, is that the worry?

2023-11-15 04:32 UTC, Goober5000 commented on code/scripting/api/objs/cockpit_display.cpp
> +	if (m_ship_info_idx < 0)
Sure.

2023-11-15 04:48 UTC, Goober5000 commented
> I was actually thinking about recently changing some `weapon_info_index` fields into just `weapon_info*`. _Technically_, being in a vector they are "dynamic", but morally, they aren't. We parse them once, and then the vector is never changed again, so theoretically pointers should still be valid? While parsing perhaps, the vector may be changing size, is that the worry?

I see where you're coming from, and in practice the pointer is likely to be safe, at least at the current time.  But I think this is one of those "err on the safe side" situations.  I can think of a few reasons to store ship and weapon info indexes rather than pointers:
1. If we should store indexes for most pointer types, then we might as well be consistent for info types as well.
2. A pointer might work today, but we could run the risk of it failing in the future for some unknown reason.  See #5785 for an example of a recent fix.  (The waypoint didn't cause problems in FSO, but did cause a crash in FRED.)
3. If someone ever implements a way to reload tables on the fly (while the engine is running), this would cause the info pointers to be invalidated.

2023-11-16 22:02 UTC, EatThePath commented
To add to the above, if the scp_pool effort comes to fruition it's use requires we store indexes instead of pointers. Anything already storing indexes can be a lot easier to convert.

2023-11-27 03:43 UTC, JohnAFernandez approved these changes

2023-11-27 04:30 UTC, merged