Make Active_games_head an SCP_list
scp-fs2open/fs2open.github.com pull request #5849
Opened 2023-11-30 21:04 UTC by MjnMixael

Converts Active_games_head to an SCP_list to prepare for the SCPUI API.

2023-12-08 16:09 UTC, JohnAFernandez commented
So, I'm going to push these back to 24.2, but I'm going to review them during the release cycle, so that it's still fresh.

2023-12-19 17:47 UTC, JohnAFernandez requested changes
So there's two main things.  I think there's a better loop structure that can be used, mostly for clarity, and there's a use of `new` from the original code that, afaict is causing small memory leaks.  AIUI `std::uniquie_pointer` is a good alternative and should handle disposal of the allocated memory.  The list would have to be changed to an `SCP_list<std::unique_pointer<active_game>>` however.

2023-12-19 19:37 UTC, MjnMixael commented on code/network/multiutil.cpp
>  	if ( new_game == nullptr ) {
Per discussion on Discord, I did away with `new` entirely. The new loop iteration method is also in place. I think that fixes up everything you noticed.

2023-12-19 19:39 UTC, JohnAFernandez approved these changes
Agreed

2024-03-03 16:01 UTC, merged