Ingame options respect mods
scp-fs2open/fs2open.github.com pull request #5917
Opened 2024-01-03 22:52 UTC by MjnMixael

This PR fixes #5697 by changing how in-game settings are saved and loaded. The key thing Wookie and I wanted here was to have these settings saved in a way that's specific to each mod but agnostic of mod versions (as far as Knossos/Nebula goes). The challenge there is that different mod versions are entirely unique mods to FSO even though Knossos knows better.

The solution this PR offers is a new ini file saved to `%appdata/HardLightProductions\FreeSpaceOpen\data`. This file is titled based on the `Cmdline_mod` parameter (`retail_fs2_settings.ini` if it's nullptr) by trimming a mod folder's version data off of it. For example, `MPVS-4.7.2` becomes `MVPS_settings.ini` and will work for all version of the MediaVPs.

There's almost certainly room for improvement here but this needs to be solved sooner rather than later and a PR will get the discussion really going.

2024-02-05 23:52 UTC, JohnAFernandez approved these changes
AFAICT, this is really well done.  It is really hard to visualize string manipulation (at least for me, so I think I would like to know what kind of test cases you guys tried before I approve, in case I (or someone else) can think of some others that we can try.

2024-02-05 23:52 UTC, JohnAFernandez commented
And then I hit the approve button.

2024-02-05 23:54 UTC, JohnAFernandez requested changes
As requested, just whatever types of test cases you guys tried, just in case.

2024-02-10 22:26 UTC, JohnAFernandez commented
I managed to get this result just by playing around with some semi-nonsense semver strings:

![Screenshot 2024-02-10 172250](https://github.com/scp-fs2open/fs2open.github.com/assets/12529946/b823c956-961e-4ebc-a435-1e04a2f39c39)

What do you think, as intended?

2024-02-12 01:36 UTC, MjnMixael commented
> Sorry for the slow reply, I'm always missing updates on github.
> 
> I managed to get this result just by playing around with some semi-nonsense semver strings:
> 
> ![Screenshot 2024-02-10 172250](https://private-user-images.githubusercontent.com/12529946/303871519-b823c956-961e-4ebc-a435-1e04a2f39c39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MDIwMDMsIm5iZiI6MTcwNzcwMTcwMywicGF0aCI6Ii8xMjUyOTk0Ni8zMDM4NzE1MTktYjgyM2M5NTYtOTYxZS00ZWJjLWE0MzUtMWUwNGEyZjM5YzM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDAxMzUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3MTAyMWYxYmRkYTM3Y2VhZjc1ZjZiMTIzN2QxOWI5YTNjYjU3ZTIzOTNjMjM5YjYxNzg2MDdkMjI5MjgyM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IT-8PPd6xuOfklfZe4jio1Xie_oklNIT4YVQ3P9rHMo)
> 
> What do you think, as intended?
> 
> FWIW, I think your test cases will handle the vast majority of cases, and something like this will probably never be chosen.

I tend to agree and even in the case of the -semver-string.semver it fellback gracefully to fs2_open.ini which is good. That's what I wanted; anything weird happens? Use fs2_open.ini.

2024-02-16 01:18 UTC, JohnAFernandez approved these changes

2024-02-21 16:53 UTC, MjnMixael commented
Please do not merge this until after #5895 is merged. There's many options-related PRs upcoming and they all touch localization...

2024-02-27 18:42 UTC, MjnMixael commented
This needs an xstr update before merge.

2024-03-25 13:36 UTC, MjnMixael commented
XSTR has been handled. This is good to merge.

2024-06-08 22:26 UTC, merged