bitstring poofs
scp-fs2open/fs2open.github.com pull request #5967
Opened 2024-01-31 04:25 UTC by Goober5000

Change `Neb2_poof_flags` to use a bit string of unlimited length to allow for an arbitrary number of nebula poofs.

In draft pending testing.

2024-02-05 22:11 UTC, JohnAFernandez requested changes
Just a couple things.  `get_int` and `set_int` are horribly generic names.  Since they are supposed to be used with bit arrays, why not something like `bit_array_get_int` and `bit_array_set_int`?

Also, some basic comments at the head of the new functions would be good.

2024-02-06 15:39 UTC, Goober5000 commented
Good points; done.

2024-02-07 04:47 UTC, JohnAFernandez approved these changes

2024-02-07 04:47 UTC, JohnAFernandez commented
Looks like a `set_int` call escaped.

2024-02-29 06:22 UTC, merged