Add waypoints-no-formation flag
scp-fs2open/fs2open.github.com pull request #6119
Opened 2024-05-01 21:59 UTC by Baezon

Ships in a wing automatically getting into formation with their wing leader when they share the same waypoint order is nice, but can surprise and frustrate fredders in certain circumstances, #6056 and $fix ai path order bug being good examples of this. They were genuine bugs which deserved fixing anyway, but sometimes its more hassle to the fredder than its worth, so this lets them turn it on and off at will.

2024-05-02 07:05 UTC, Goober5000 requested changes
There isn't really a way to set wing flags unless you are using scripting or you specify the flag in the mission file.  (And in the latter case, you'd need to add FRED support.)  I would recommend taking that out.

This PR also has a ship flag which looks redundant to the AI flag.  It also isn't checked in the `ai_formation()` condition.

2024-05-03 14:12 UTC, Goober5000 commented
> Wing flags can be changed via alter-wing-flag, that and alter-ship-flag were the main ways I expected this to be used.

Ah, fair enough.  I missed the `alter-wing-flag` sexp.

> Also, where is this redundant flag?

Since both the `alter-ship-flag` sexp and the `ship:setFlag` scripting function check both AI flags and ship flags, there isn't a need to have both flags.

2024-05-03 16:06 UTC, Baezon commented
Can you point to a specific line? I added a wing flag and an AI flag, there isn't actually a ship flag.

2024-05-05 21:16 UTC, Goober5000 commented
Bleh, you're right.  My brain linked ship_flags.h with a ship flag, even though it was a wing flag.

2024-05-05 21:16 UTC, Goober5000 approved these changes
Everything looks good 👍

2024-05-06 02:10 UTC, merged