Conditional Impacts followup
scp-fs2open/fs2open.github.com pull request #6254
Opened 2024-07-15 02:32 UTC by Kestrellius

This is a follow up to [#6218](https://github.com/scp-fs2open/fs2open.github.com/pull/6218), and makes a few changes.

First, I switched the ordering of a couple of the table lines. Previously, the armor type came first, then the effect name, then the other conditions. However, the armor type is a condition, whereas the effect is what happens when the conditions are met, and I thought that each of those things should be clustered. So now, the effect name goes at the end.

This is modder-facing, but the feature was merged like a week ago and I would be very surprised if anyone had used it yet, so I expect it'll be fine.

Second, I added support for conditional impacts when hitting weapons (such as bombs). This got a little thornier than I anticipated, and required making a significant change in collideweaponweapon.cpp -- weapon-weapon impacts now call weapon_hit(), where previously they just set the weapon's lifetime to a very low value and let lifetime expiration take care of it.

This is sort of a big alteration. I'm not sure I've correctly understood all the implications, and I won't be surprised if the PR is rejected for this reason. (Now that I think of it, I should have put these two changes in separate branches. Oh well -- they're simple; if I need to I can split them out manually without much trouble.) There is one change in behavior that I can think of, though it's purely cosmetic: before, hitting a weapon wouldn't play the impact effect (unless 'detonate on expiration' was set), whereas now it will. Possibly there's some mod somewhere whose art style was importantly dependent on this?

2024-07-17 22:08 UTC, Baezon requested changes
The main difference I can see is that there would be hit sounds for lasers hitting bombs. Leaving aside whether this should have been allowed as a separate issue... should be simple enough to check if the other object is a weapon in `weapon_hit_do_sound`, and not play sounds in that case.

2024-07-21 12:28 UTC, Kestrellius commented
> The main difference I can see is that there would be hit sounds for lasers hitting bombs. Leaving aside whether this should have been allowed as a separate issue... should be simple enough to check if the other object is a weapon in `weapon_hit_do_sound`, and not play sounds in that case.

Okay. So, as best as I can tell, it should already work like this. There's a switch in weapon_hit_do_sound, conditioned on the weapon being a non-missile, and it checks for OBJ_SHIP and OBJ_ASTEROID, and then the default just returns. Without playing a sound, as far as I can determine. So if we have a non-missile hitting a weapon, it should end up in that default and not play a sound.

2024-07-21 17:08 UTC, Baezon approved these changes
Ah, yes, you are right. It should be ok then otherwise, as far as I can tell. The other collision handling pair functions already use `weapon_hit`.

2024-07-27 18:01 UTC, wookieejedi commented
This one appears ready to merge? Just checking specifically b/c it is the past 24.2 marked PR

2024-07-27 18:42 UTC, Kestrellius commented
Should be ready to merge, yeah!

2024-07-28 18:08 UTC, wookieejedi commented
Sounds good. Will merge today or tomorrow if no one else beats me to it.

2024-07-29 20:35 UTC, merged