Fixes CTD with new Friendly Fire Feature
scp-fs2open/fs2open.github.com pull request #6302
Opened 2024-08-15 20:33 UTC by wookieejedi

On current master I was hitting a CTD when firing a weapon with a shockwave at close range (ie player is within the shockwave zone). The minidump showed `other_obj` was null, so this PR adds some safety checks.

Tested and this fixes the crashes.

2024-08-16 04:00 UTC, Goober5000 requested changes
I believe this is actually the wrong fix, and that almost all of the `other_obj` references should instead be `objp`.  The checks here are dealing primarily with the *objp* receiving the area effect, not the *other_obj* that was actually impacted.  In fact, for clarity, `other_obj` should be renamed something like `impacted_obj`.

2024-08-16 16:54 UTC, wookieejedi commented
Just for convenience I copied the part of 6265 that was new in this file:
![Changed Sections](https://github.com/user-attachments/assets/7e7177b1-8799-4e88-bc4a-10e975335f09)


Also, renaming `other_obj` to `impacted_obj` would of course touch a lot of this entire function, but if that's the agreed upon course of action I can change it.

2024-08-16 21:04 UTC, Goober5000 commented
Most of the current `other_obj` references should be `objp`, so after that is fixed, renaming `other_obj` will not touch much.

2024-08-17 18:13 UTC, Goober5000 approved these changes
Quite a tricky bug to solve, but this looks good now. 👍

2024-08-17 18:30 UTC, merged