Lua hooks for the comm board
scp-fs2open/fs2open.github.com pull request #6450
Opened 2024-12-05 22:56 UTC by MjnMixael

This adds a few useful features to get full access to the comm board and enhance or entirely replace its functionality.

- mn.CommItems grants access to the current menu items. This is not just 0-9 visible items but also any items that could be paged to using PgUp or PgDn. CommItems come with `Name`, `Active` (whether the item can be selected or not), `getMenuTitle()` to get the current title of the menu, `selectItem()` which selects it and either moves to the next menu or activates the order, and `isValid()`.
- `On HUD Comm Order Issued` overridable hook that runs when an AI order is issued via the comm board. It comes with hook variables for the Sender, the Recipient, the Target, the target Subsystem, the Order enumeration, and the visible Name of the order as it appears on the comm board.
- `mn.sendBuiltinMessage()` which works exactly like the `send-builtin-message` SEXP

2025-03-16 09:01 UTC, BMagnu requested changes
Okay, finally got around to this one.
Small change, some question, and request for hook conditions.

2025-03-16 09:01 UTC, BMagnu commented on code/scripting/global_hooks.cpp
> +const std::shared_ptr<OverridableHook<>> OnHudCommOrderIssued = OverridableHook<>::Factory("On HUD Comm Order Issued",
So, I think this hook would massively benefit from having proper hook conditions.
Ship class / type / name of the target, same + eventual wing name for the recipient, maybe the sender.

2025-03-16 13:54 UTC, MjnMixael commented on code/scripting/global_hooks.cpp
> +const std::shared_ptr<OverridableHook<>> OnHudCommOrderIssued = OverridableHook<>::Factory("On HUD Comm Order Issued",
I'm not sure how to do conditions. What's a good one to look at for examples?

2025-03-28 14:07 UTC, MjnMixael commented on code/scripting/api/libs/mission.cpp
> +ADE_LIB_DERIV(l_Mission_Comm_Items, "CommItems", nullptr, "Comm Items in the mission", l_Mission);
Hmm maybe. At the same time, this is only valid while in an active mission so while I could go either way, I think this one leans more towards being part of Mission?

2025-03-28 15:33 UTC, MjnMixael commented on code/scripting/api/libs/mission.cpp
> +	if (sender_ship_h == nullptr || !sender_ship_h->isValid())
our Lua Enums system really needs a re-think... This long list is pretty brittle for error checking but I put in a basic check for now.

2025-03-28 15:33 UTC, MjnMixael commented on code/scripting/global_hooks.cpp
> +const std::shared_ptr<OverridableHook<>> OnHudCommOrderIssued = OverridableHook<>::Factory("On HUD Comm Order Issued",
No idea if I did it right, but a basic setup for conditions is there now.

2025-03-29 14:10 UTC, naomimyselfandi requested changes
I found what looks likes a memory leak, and have a few requests around custom builtin messages.

2025-03-29 14:10 UTC, naomimyselfandi commented on code/scripting/api/objs/enums.cpp
> +	{"BUILTIN_MESSAGE_ATTACK_TARGET", LE_BUILTIN_MESSAGE_ATTACK_TARGET, true},
You could autogen this the same way as the other builtin message stuff, so that new types are automatically registered here:
```cpp
#define X(NAME, ...) {"BUILTIN_MESSAGE_" # NAME, LE_BUILTIN_MESSAGE_ ## NAME, true },
BUILTIN_MESSAGE_TYPES
#undef X
```

2025-03-29 14:10 UTC, naomimyselfandi commented on code/scripting/api/objs/enums.h
> +	LE_BUILTIN_MESSAGE_ATTACK_TARGET,
See above:
```cpp
#define X(NAME, ...) LE_BUILTIN_MESSAGE_ ## NAME,
BUILTIN_MESSAGE_TYPES
#undef X
```

2025-03-29 14:11 UTC, naomimyselfandi commented on code/scripting/api/libs/mission.cpp
> +	if (sender_ship_h == nullptr || !sender_ship_h->isValid())
What about giving each Lua enum a "category" (an `enum class`) and checking that? Out of scope for this PR, of course.

2025-03-29 15:30 UTC, MjnMixael commented on code/scripting/api/objs/enums.cpp
> +	{"BUILTIN_MESSAGE_ATTACK_TARGET", LE_BUILTIN_MESSAGE_ATTACK_TARGET, true},
The Lua enum list is long and terrible and needs a complete redesign, indeed. But I'd rather match the rest of the enums than try to fix it here by doing something different than all the other enums in the list. That and these are in an array for the Lua Enums to code to work with so I'm not sure your version of autogen will work in this instance. They'd have to be genned and then inserted.

2025-03-29 15:30 UTC, MjnMixael commented on code/hud/hudsquadmsg.cpp
> +LOCAL bool Msg_key_set_from_scripting;      // is true if the key was set from scripting and not from a player keypress
Done

2025-03-29 15:31 UTC, MjnMixael commented on code/hud/hudsquadmsg.cpp
> +		object_ship_wing_point_team* recipient = nullptr;
Good catch. Done.

2025-03-29 15:33 UTC, MjnMixael commented on code/scripting/api/libs/mission.cpp
> +	enum_h* ehp = nullptr;
As I mentioned earlier, it's gonna be a while before I have the brain capacity to try and understand custom built-ins enough to add support for them here. This PR will have to wait again until I can do that.

2025-03-29 15:34 UTC, MjnMixael commented on code/mission/missionmessage.h
> +	Num_Message_Types
Easy change, but see below.

2025-03-29 16:45 UTC, BMagnu requested changes
Just some tiny final changes, otherwise this looks good now

2025-03-29 16:45 UTC, BMagnu commented on code/hud/hudsquadmsg.cpp
> +		}
This shouldn't be a pointer at all in the first place.
Make it a default / empty oswpt object (without a pointer), and reassign it if either of these criteria is met.
Otherwise, if it stays nullptr, it'll explode when dereferencing for the parameter list anyways.

2025-03-29 16:45 UTC, BMagnu commented on code/scripting/api/libs/mission.cpp
> +	enum_h* ehp = nullptr;
This can be deferred to the future if desired.
I'd agree that using a shared parameter that has a message-type enum for builtins and a string for custom messages is best. And since that just adds API options instead of invalidating old ones, it's safe to just not support it for now.

2025-03-29 16:45 UTC, BMagnu commented on code/scripting/hook_conditions.cpp
> +HOOK_CONDITIONS_END
By adding a `HOOK_CONDITION_SHIP_OBJP` (and similarly doing the prefix thing you did for `HOOK_CONDITION_SHIPP`, you can add a one-liner to allow conditions based on "Target Ship", and "Target Ship Class" and "Target Ship type". These will automatically never match if your objp is not a ship, so you don't need any more additional handling.

Receiving ships can wait for now, since the required OSWPT handling methods don't exist yet, and coding them in here is a bit beyond scope.

2025-03-29 16:47 UTC, BMagnu commented on code/scripting/api/objs/enums.cpp
> +	{"BUILTIN_MESSAGE_ATTACK_TARGET", LE_BUILTIN_MESSAGE_ATTACK_TARGET, true},
I concur with Mjn here, while getting Lua enums proper would be good, it's out of scope for this.
We ideally want a PR that properly refactors enums in a way that they no longer are the same type for totally different enums, but which also keeps script compatibility.
But that's definitely its own PR

2025-03-29 16:58 UTC, MjnMixael commented on code/mission/missionmessage.h
> +	Num_Message_Types
Done

2025-03-29 16:58 UTC, MjnMixael commented on code/scripting/api/libs/mission.cpp
> +	enum_h* ehp = nullptr;
Naomi gave me the roadmap in PMs so this has been addressed now.

2025-03-29 17:06 UTC, naomimyselfandi commented on code/scripting/api/objs/enums.cpp
> +	{"BUILTIN_MESSAGE_ATTACK_TARGET", LE_BUILTIN_MESSAGE_ATTACK_TARGET, true},
(I think you realized this, but just to be sure we're on the same page, the generation works by transforming the source code with preprocessor macros. This specific technique is called an X-macro, and it's one of the few applications of macros that (to my knowledge) can't be replaced by C++ templates.)

I'm fine with leaving cleaning up this list as an Indefinite Future Thing(TM). Could you add a comment to missionmessage.h saying that new standard builtin messages should be added here too?

2025-03-29 17:19 UTC, MjnMixael commented on code/scripting/api/objs/enums.cpp
> +	{"BUILTIN_MESSAGE_ATTACK_TARGET", LE_BUILTIN_MESSAGE_ATTACK_TARGET, true},
A comment was kinda already there. I expanded it.

2025-03-29 17:19 UTC, MjnMixael commented on code/hud/hudsquadmsg.cpp
> +		}
I think I fixed that correctly then.

2025-03-29 17:19 UTC, MjnMixael commented on code/scripting/hook_conditions.cpp
> +HOOK_CONDITIONS_END
Done.

2025-04-01 09:11 UTC, BMagnu requested changes
Almost all good now, just a tiny oversight.

2025-04-01 09:11 UTC, BMagnu commented on code/scripting/hook_conditions.cpp
> +#define HOOK_CONDITION_SHIP_OBJP(classname, prefix, documentationAddendum, objp_) \
That prefix will need to also apply to the other two conditions generated by this macro

2025-04-01 13:01 UTC, MjnMixael commented on code/scripting/hook_conditions.cpp
> +#define HOOK_CONDITION_SHIP_OBJP(classname, prefix, documentationAddendum, objp_) \
Done

2025-04-01 13:05 UTC, BMagnu approved these changes

2025-04-02 22:55 UTC, merged